// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "chat": {
    "activity": {
      "command": "{{count}} command" | "{{count}} commands",
      "created": "created {{count}}" | "created {{count}}",
      "edited": "edited {{count}}" | "edited {{count}}",
      "failed": "{{count}} failed" | "{{count}} failed",
      "fallback": "Activity",
      "other_tool": "{{count}} × {{tool}}" | "{{count}} × {{tool}}",
      "read": "read {{count}} file" | "read {{count}} files",
      "single_failed": "{{title}} · failed",
      "thought": "thought",
      "thought_seconds": "thought for {{count}} s" | "thought for {{count}} s",
      "working": "Working…"
    },
    "approval": {
      "no": "No",
      "yes": "Yes"
    },
    "chain_of_thought": {
      "title": "Chain of thought"
    },
    "composer": {
      "effort": {
        "placeholder": "Effort (default)",
        "title": "Reasoning effort, takes effect from the next run"
      },
      "model": {
        "placeholder": "Model (default)",
        "title": "Model"
      },
      "placeholder": {
        "default": "Write a message…",
        "elsewhere": "The transcript is on the device {{host}}. Continue there, or have the thread handed off.",
        "waiting": "The thread is waiting for an answer to the question above."
      },
      "runner": {
        "default_option": "{{label}} (default)",
        "title": "Runner and instance, set for the whole thread; only a new thread can change it"
      },
      "stop": "Stop",
      "submit": "Send"
    },
    "context": {
      "cache": "Cache",
      "input": "Input",
      "output": "Output",
      "percent": "{{percent}}%",
      "ring_label": "Context window usage",
      "tokens": "{{tokens}} token" | "{{tokens}} tokens",
      "under_one_percent": "<1%"
    },
    "conversation": {
      "empty": {
        "description": "Write the first message below.",
        "title": "No messages yet"
      },
      "loading": "Loading the conversation…"
    },
    "elsewhere": {
      "hint": "The thread ran on the device {{host}} and its content stays there; Portuni does not copy conversations anywhere. To continue it here, use Hand off there and continue from the handoff file in the Threads tab.",
      "title": "The transcript is on the device {{host}}"
    },
    "error": {
      "save_effort": "Could not save the effort: {{error}}",
      "save_model": "Could not save the model: {{error}}",
      "save_runner": "Could not save the runner and instance: {{error}}"
    },
    "event": {
      "denied": {
        "connector_disabled": "This connector is turned off for the run. The agent should use the Portuni server.",
        "denied_by_user": "You declined.",
        "not_answered": "The question was not answered.",
        "run_ended": "The run ended before an answer arrived.",
        "turn_stopped": "The turn was stopped before an answer arrived.",
        "write_no_path": "The {{tool}} call has no {{field}}, so the write could not be checked.",
        "write_outside_mirror": "Writing to {{path}} was blocked: it is outside this node's mirror.",
        "write_outside_root": "Writing to {{path}} was blocked: it is outside the Portuni folder."
      },
      "error": {
        "browser_sign_in_declined": "{{server}} asked for a sign-in in a browser. The chat cannot open one, so the request was declined.",
        "provider_failed": "The run ended with a provider error ({{subtype}}).",
        "provider_not_logged_in": "Claude Code is not signed in on this device."
      },
      "question": {
        "agent_question": {
          "title": "Question from the agent"
        },
        "mcp_confirmation": {
          "title": "Confirm for {{server}}"
        },
        "plan_approval": {
          "title": "Approve the plan?"
        },
        "scope_expand": {
          "detail": "The agent wants to read a node outside this thread's current scope.",
          "title": "Expand the thread's scope?"
        }
      }
    },
    "file_change": {
      "create": "created",
      "delete": "deleted",
      "edit": "edited",
      "rename": "renamed"
    },
    "header": {
      "cancel_rename": "Cancel",
      "close": "Close thread",
      "closing": "Closing…",
      "continue": "Continue in a new thread",
      "continuing": "Continuing…",
      "hand_off": "Hand off to another device",
      "handing_off": "Handing off…",
      "rename": "Rename",
      "save_name": "Save name"
    },
    "loader": {
      "title": "Loading"
    },
    "message": {
      "next_branch": "Next branch",
      "previous_branch": "Previous branch"
    },
    "model": {
      "description": {
        "balanced": "Balanced model for everyday work.",
        "fastest": "The fastest and cheapest model.",
        "most_capable": "The most capable model, slower and more expensive."
      }
    },
    "notice": {
      "dismiss": "Hide",
      "handed_off": "The thread is handed off. The summary is in <code>{{path}}</code>; once it syncs, continue from it on the other device in the Threads tab.",
      "suspended": "The process has ended. The next message starts the conversation again, and the context so far goes to the model once more."
    },
    "question": {
      "answer_placeholder": "Answer…",
      "send": "Send"
    },
    "reasoning": {
      "step_label": "Reasoning",
      "thinking": "Thinking…",
      "thought_few_seconds": "Thought for a few seconds",
      "thought_for": "Thought for {{count}} s" | "Thought for {{count}} s"
    },
    "sample": {
      "message": "Thread with {{runnerName}}."
    },
    "streamdown": {
      "close": "Close",
      "copied": "Copied",
      "copy_code": "Copy code",
      "copy_link": "Copy link",
      "copy_table": "Copy table",
      "copy_table_as_csv": "Copy table as CSV",
      "copy_table_as_markdown": "Copy table as Markdown",
      "copy_table_as_tsv": "Copy table as TSV",
      "download_diagram": "Download diagram",
      "download_diagram_as_mmd": "Download diagram as MMD",
      "download_diagram_as_png": "Download diagram as PNG",
      "download_diagram_as_svg": "Download diagram as SVG",
      "download_file": "Download file",
      "download_image": "Download image",
      "download_table": "Download table",
      "download_table_as_csv": "Download table as CSV",
      "download_table_as_markdown": "Download table as Markdown",
      "exit_fullscreen": "Exit full screen",
      "external_link_warning": "You are about to open an external website.",
      "image_not_available": "Image not available",
      "mermaid_format_mmd": "MMD",
      "mermaid_format_png": "PNG",
      "mermaid_format_svg": "SVG",
      "open_external_link": "Open the external link?",
      "open_link": "Open link",
      "reset_view": "Reset zoom and pan",
      "table_format_csv": "CSV",
      "table_format_markdown": "Markdown",
      "table_format_tsv": "TSV",
      "view_fullscreen": "View full screen",
      "zoom_in": "Zoom in",
      "zoom_out": "Zoom out"
    },
    "tool": {
      "error": "Error",
      "parameters": "Parameters",
      "result": "Result",
      "status": {
        "completed": "Completed",
        "failed": "Error",
        "started": "Running"
      }
    },
    "transcript": {
      "compaction": "Context compacted",
      "interrupted": "Interrupted",
      "question": "Question: <title>{{title}}</title>",
      "run_ended": {
        "error": "The run ended with an error.",
        "host_lost": "The run ended: its process was orphaned.",
        "limit": "The run ended: the provider's limit was reached.",
        "other": "The run ended: {{reason}}"
      },
      "summary_saved": "Summary saved"
    },
    "working": {
      "continuing": "Continuing…",
      "elapsed": "{{count}} s" | "{{count}} s",
      "starting": "Starting…",
      "thinking": "Thinking…"
    }
  },
  "common": {
    "app": {
      "editor_guard": {
        "back_to_editor": "Back to editor",
        "description": "The file in the editor has unsaved changes. Do you want to save them?",
        "description_quit": "The file in the editor has unsaved changes. Do you want to save them before closing the app?",
        "discard": "Discard changes",
        "save": "Save",
        "saving": "Saving…",
        "title": "Unsaved changes"
      },
      "graph_error": {
        "hint": "Is the Portuni server running on port 4011?",
        "title": "Couldn't load the graph"
      },
      "graph_loading": "Loading graph…",
      "thread_error": {
        "handoff_failed": "Couldn't hand off the thread: {{error}}",
        "load_failed": "Couldn't load the node's threads: {{error}}",
        "rename_failed": "Couldn't rename the thread: {{error}}"
      }
    },
    "create_node": {
      "cancel": "Cancel",
      "field": {
        "description": "Description",
        "name": "Name",
        "organization": "Organization",
        "type": "Type"
      },
      "hint": {
        "first_organization": "You're starting by creating your first organization, so the type is preset.",
        "name_min_length": "The name must be at least {{count}} character long." | "The name must be at least {{count}} characters long."
      },
      "no_organizations": "Create an organization first, then come back here.",
      "placeholder": {
        "description": "Short description (optional)",
        "name_default": "Client onboarding",
        "name_organization": "Acme Inc."
      },
      "submit": "Create",
      "submitting": "Creating…",
      "title": "New node"
    },
    "date_picker": {
      "next_month": "Next month",
      "previous_month": "Previous month"
    },
    "editor": {
      "back": "Back",
      "back_title": "Back to details",
      "close_title": "Close editor",
      "codemirror": {
        "all": "all",
        "by_word": "by word",
        "close": "close",
        "completions": "Completions",
        "control_character": "Control character",
        "current_match": "current match",
        "diagnostics": "Diagnostics",
        "find": "Find",
        "fold_line": "Fold line",
        "folded_code": "folded code",
        "folded_lines": "Folded lines",
        "go": "go",
        "go_to_line": "Go to line",
        "match_case": "match case",
        "next": "next",
        "no_diagnostics": "No diagnostics",
        "on_line": "on line",
        "previous": "previous",
        "regexp": "regexp",
        "replace": "replace",
        "replace_all": "replace all",
        "replace_field": "Replace",
        "replaced_match_on_line": "replaced match on line $",
        "replaced_matches": "replaced $ matches",
        "selection_deleted": "Selection deleted",
        "to": "to",
        "unfold": "unfold",
        "unfold_line": "Unfold line",
        "unfolded_lines": "Unfolded lines"
      },
      "collapse_title": "Shrink to panel",
      "conflict": {
        "keep_mine": "Keep mine",
        "message": "The file changed on disk in the meantime.",
        "reload_theirs": "Load theirs"
      },
      "expand_title": "Full window",
      "external_change": {
        "message": "The file changed on disk.",
        "reload": "Load the current version"
      },
      "html_preview": {
        "copied": "Copied",
        "copy_path": "Copy path",
        "copy_path_title": "Copy the file path",
        "deck_without_node": "The deck doesn't belong to any node.",
        "frame_title_html": "HTML preview",
        "frame_title_showtime": "Presentation preview",
        "open_in_browser": "Open in browser",
        "open_in_showtime": "Open in Showtime",
        "open_in_showtime_title": "Open the deck in the Showtime app with the node's context"
      },
      "loading": "Loading…",
      "mode": {
        "edit": "Edit",
        "group_label": "Editor mode",
        "preview": "Preview"
      },
      "save": "Save",
      "save_title": "Save (Cmd/Ctrl+S)",
      "saving": "Saving…"
    },
    "error_boundary": {
      "retry": "Try rendering again",
      "title": "Portuni hit an error while rendering. Copy the text below and switch back to a working agent."
    },
    "error_overlay": {
      "dismiss": "Hide",
      "title": "Portuni hit an error (this panel replaces a blank white screen). Copy the text below."
    },
    "footer": {
      "mcp": {
        "label_down": "mcp ×",
        "label_loading": "mcp…",
        "label_running": "mcp",
        "title_down": "MCP server unavailable: {{reason}}",
        "title_loading": "Checking the MCP server…",
        "title_running": "MCP server is running: {{url}}"
      },
      "pull": {
        "label": "{{count}} node on the remote" | "{{count}} nodes on the remote",
        "title": "The remote watcher found newer versions of files. Open the sync overview."
      },
      "threads": {
        "label": "{{count}} thread" | "{{count}} threads",
        "title": "Active threads: {{runningCount}}"
      },
      "unsynced": {
        "label": "↑ {{pendingCount}} unsynced",
        "title": "Unsynced: {{count}} file" | "Unsynced: {{count}} files"
      },
      "update": {
        "available_label": "↑ {{version}}",
        "available_title": "New Portuni version – click to update",
        "ready_label": "Restart",
        "ready_title": "Restart to finish the update"
      }
    },
    "gate": {
      "central_login": {
        "not_configured": "This is a team workspace, but its configuration is missing. Add <code>server_url</code> and <code>google_client_id</code> to <code>config.json</code>.",
        "prompt": "Sign in with Google to access the shared graph.",
        "submit": "Sign in with Google",
        "submitting": "Signing in…",
        "title": "Portuni"
      },
      "first_steps": {
        "confirm": "Got it, open Portuni",
        "description": "You'll see the shared graph right away; what you can see in it is governed by permissions on the server.",
        "mirrors": "Mirrors on your Mac are created node by node: open a node in the graph and click <label>New task</label> or the folder icon in the node's header. Portuni creates the node's local folder and pulls its files. Without this step, the content stays only on the server.",
        "title": "You're signed in"
      },
      "setup": {
        "join_team": {
          "description": "Your organization already runs a Portuni server. Enter its address, then sign in with your Google account.",
          "error_empty_url": "The server address can't be empty.",
          "submit": "Connect",
          "submitting": "Connecting…",
          "title": "Join a team",
          "url_placeholder": "api.your-company.com"
        },
        "personal": {
          "description": "Only on this Mac, no account. Good for trying Portuni out.",
          "submit": "Create personal workspace",
          "title": "Personal workspace"
        },
        "subtitle": "How do you want to start?",
        "title": "Welcome to Portuni"
      },
      "turso": {
        "description": "Portuni connects to a remote Turso database. Paste the auth token; we'll store it in the macOS Keychain and restart the backend.",
        "error_empty_token": "The token can't be empty.",
        "submit": "Save and restart",
        "submitting": "Saving…",
        "title": "Connect to Turso",
        "token_placeholder": "eyJhbGciOiJFZERTQSIs…"
      },
      "workspace_migration": {
        "description": "Portuni now supports multiple workspaces. Your existing data moves under the name you choose, and the name can't be changed afterwards.",
        "id_invalid": "ID: (invalid)",
        "id_preview": "ID: {{id}}",
        "submit": "Continue",
        "submitting": "Migrating…",
        "title": "Name your workspace"
      }
    },
    "node_list": {
      "activity": {
        "running": "A task is running",
        "waiting": "A task is waiting for an answer"
      },
      "empty_nodes": "No open nodes. Open a node with Search nodes (⌘K) or create a new one.",
      "empty_tasks": "No tasks. Start a task from a node's detail with the New task button.",
      "group": {
        "done": "Done",
        "draft": "New",
        "running": "Working",
        "suspended": "Suspended",
        "waiting": "Need attention"
      },
      "heading": "Open",
      "mode": {
        "aria_label": "Arrangement",
        "nodes": "Nodes",
        "nodes_title": "Group by node",
        "state": "Status",
        "state_title": "Tasks only, by status"
      },
      "node": {
        "close": "Close node",
        "new_task_aria_label": "New task",
        "new_task_title": "New task for this node"
      },
      "task": {
        "close": "Close thread",
        "handoff": "Hand off to another device",
        "state": {
          "done": "Done",
          "draft": "New",
          "running": "Running",
          "suspended": "Suspended",
          "waiting": "Waiting for an answer"
        }
      }
    },
    "node_type": {
      "area": "Area",
      "organization": "Organization",
      "principle": "Principle",
      "process": "Process",
      "project": "Project"
    },
    "overview": {
      "activity": {
        "empty": "No activity yet.",
        "session_write": "{{sessionName}} wrote to {{nodeName}}",
        "title": "Recent activity"
      },
      "attention": {
        "access_request": "Access request: {{userName}}",
        "empty": "Nothing needs attention.",
        "sync_issue": "Sync problem: {{nodeName}}",
        "title": "Needs attention"
      },
      "counter": {
        "attention": "Needs attention",
        "running": "Running",
        "unsynced": "Not synced",
        "waiting": "Waiting on me"
      },
      "loading": "Loading the overview…",
      "new_nodes": {
        "empty": "No recently created nodes.",
        "title": "New nodes"
      },
      "refresh": "Refresh",
      "show_all": "Show {{count}}" | "Show all {{count}}",
      "threads": {
        "cli": "Plus {{count}} CLI session ({{running}} running)" | "Plus {{count}} CLI sessions ({{running}} running)",
        "empty": "No running or suspended threads.",
        "no_node": "Chat",
        "no_reason": "no reason given",
        "review_queue": "Review queue (disconnected jumps)",
        "title": "Threads"
      },
      "title": "Overview"
    },
    "palette": {
      "description": "Type a node name and press Enter.",
      "empty": "No nodes",
      "footer": {
        "close": "Close",
        "navigate": "Navigate",
        "open": "Open"
      },
      "key": {
        "enter": "Enter",
        "esc": "Esc"
      },
      "placeholder": "Search nodes…",
      "title": "Search nodes"
    },
    "quit_guard": {
      "cancel": "Cancel",
      "close_without_sync": "Close without syncing",
      "description": "You have {{count}} file that isn't on the remote (unsynced). If you close the app, it stays only on this device." | "You have {{count}} files that aren't on the remote (unsynced). If you close the app, they stay only on this device.",
      "show_and_sync": "Show and sync",
      "title": "Unsynced work"
    },
    "sample": {
      "items": "{{count}} item" | "{{count}} items",
      "link": "Open <link>settings</link>.",
      "message": "Welcome to Portuni, {{userName}}."
    },
    "sidebar": {
      "brand": "Portuni",
      "create": {
        "button": "New node",
        "denied": "Creating nodes requires a higher role",
        "title_graph": "Create a new node (organization, project, process, area, principle)",
        "title_work": "Creates a new node and opens it in Work"
      },
      "filters": {
        "node_types": "Node types",
        "organizations": "Organizations",
        "relation_types": "Relation types",
        "status": "Status",
        "status_value": {
          "active": "Active",
          "archived": "Archived",
          "completed": "Completed"
        },
        "summary": "Overview",
        "summary_nodes": "Nodes",
        "summary_relations": "Relations"
      },
      "footer": {
        "graph": "Click a node to open its detail. Drag to pan, scroll to zoom.",
        "settings": "Changes are saved automatically."
      },
      "hint": {
        "overview": "A summary of the whole workspace: running threads, nodes that need attention, recent activity and newly created nodes.",
        "settings": "Portuni configuration: the agent command for launching from nodes and the MCP server parameters for Claude Code and Codex."
      },
      "search": {
        "button": "Search nodes…",
        "title": "Search nodes ({{shortcut}})"
      },
      "settings": "Settings",
      "theme": {
        "to_dark": "Switch to dark mode",
        "to_light": "Switch to light mode"
      },
      "view": {
        "graph": "Graph",
        "group_label": "View",
        "overview": "Overview",
        "work": "Work"
      },
      "workspace_switcher": {
        "aria_label": "Workspace",
        "hint": {
          "disabled": "disabled",
          "open": "open",
          "this_window": "this window",
          "unavailable": "unavailable"
        },
        "manage": "Manage workspaces…",
        "placeholder": "Workspace",
        "title": "Open another workspace"
      }
    },
    "thread": {
      "composer": {
        "placeholder": {
          "archived": "This thread is archived.",
          "open": "Write a message…"
        }
      },
      "state": {
        "header": {
          "archived": "Archived",
          "closed": "Closed",
          "draft": "New",
          "running": "Running",
          "suspended": "Suspended"
        },
        "row": {
          "archived": "Archived",
          "closed": "Done",
          "draft": "New",
          "running": "Running",
          "suspended": "Suspended"
        },
        "waiting": "Waiting on me"
      }
    },
    "ui": {
      "command": {
        "description": "Search for a command to run…",
        "title": "Command palette"
      },
      "dialog": {
        "close_button": "Close",
        "close_label": "Close"
      },
      "spinner": {
        "loading": "Loading"
      }
    },
    "workspace": {
      "empty": {
        "description": "Open any node and work on it. You can have several nodes open and switch between them.",
        "search_placeholder": "Search nodes…",
        "title": "Open a node in Work"
      },
      "pick_node_hint": "Select a node on the left.",
      "show_node_detail": "Show node detail"
    }
  },
  "desktop": {
    "login": {
      "failure": "Sign-in failed. Return to Portuni and try again.",
      "success": "Sign-in complete. You can return to Portuni."
    },
    "menu": {
      "quit": "Quit Portuni"
    }
  },
  "errors": {
    "ACCESS_ALREADY_VISIBLE": "You already have access.",
    "ACCESS_DUPLICATE_ENTRIES": "Someone is in the access list twice.",
    "ACCESS_GROUP_NEEDS_ENTRIES": "Group visibility needs at least one person or group.",
    "ACCESS_REQUEST_NOT_FOUND": "The access request was not found.",
    "ACCESS_REQUEST_PENDING": "Your access request is already waiting.",
    "ACCESS_REQUEST_RESOLVED": "The access request has already been resolved.",
    "ACCESS_UNKNOWN_USERS": "{{count}} user in the access list does not exist." | "{{count}} users in the access list do not exist.",
    "BEARER_MISMATCH": "Your sign-in is no longer valid. Sign in again.",
    "BEARER_MISSING": "You are not signed in.",
    "BODY_TOO_LARGE": "The request is too large.",
    "CENTRAL_UNREACHABLE": "The central server is unreachable.",
    "CONFIRMATION_REQUIRED": "The action needs a confirmation.",
    "CONFLICT": "The file changed since you opened it.",
    "CONSTRAINT_VIOLATION": "The change conflicts with existing data.",
    "DATA_SOURCE_NOT_FOUND": "The data source was not found.",
    "DATA_SOURCE_TARGET_INVALID": "Data sources can be added only to a project, process or area.",
    "DESKTOP_BACKEND_EXITED": "The local server stopped (exit code {{exitCode}}).",
    "DESKTOP_BACKEND_FAILED": "The local server did not start: {{detail}}",
    "DESKTOP_BACKEND_NOT_READY": "The local server is not running yet.",
    "DESKTOP_BROWSER_OPEN_FAILED": "The browser could not be opened: {{detail}}",
    "DESKTOP_CONFIG_INVALID": "The app settings file cannot be read: {{detail}}",
    "DESKTOP_CONFIG_MISSING": "The app is not set up yet.",
    "DESKTOP_CONFIG_NOT_MIGRATED": "The app settings have not been moved to workspaces yet.",
    "DESKTOP_CONFIG_UNAVAILABLE": "The server has no sign-in settings for the desktop app.",
    "DESKTOP_LOGIN_NOT_CONFIGURED": "Sign-in is not set up for this workspace: the server address or the Google client is missing.",
    "DESKTOP_LOGIN_NOT_ENABLED": "The central server does not have Google sign-in turned on yet.",
    "DESKTOP_LOGIN_REJECTED": "The central server did not accept the Google sign-in.",
    "DESKTOP_LOGIN_STATE_MISMATCH": "Sign-in was refused because the browser's answer does not match the request. Try again.",
    "DESKTOP_LOGIN_TIMEOUT": "Sign-in timed out waiting for the browser.",
    "DESKTOP_MCP_INSTALL_PARTIAL": "Some workspaces could not be connected: {{detail}}",
    "DESKTOP_NOT_HTML": "Only an HTML file can be opened in the browser.",
    "DESKTOP_NOT_SHOWTIME_DECK": "Only a .showtime deck can be opened in Showtime.",
    "DESKTOP_NOT_WORKSPACE_WINDOW": "This window does not belong to a workspace.",
    "DESKTOP_NO_WIP_DIR": "The node's mirror has no wip folder.",
    "DESKTOP_OPEN_FAILED": "The file could not be opened: {{detail}}",
    "DESKTOP_PATH_NOT_FOUND": "“{{path}}” does not exist.",
    "DESKTOP_PATH_OUT_OF_SCOPE": "The file is outside this workspace's folder.",
    "DESKTOP_SERVER_ERROR": "The server answered with an error (HTTP {{status}}).",
    "DESKTOP_SERVER_UNREACHABLE": "The server is unreachable: {{detail}}",
    "DESKTOP_SERVER_URL_INSECURE": "http:// is allowed only for localhost; use https://.",
    "DESKTOP_SERVER_URL_REQUIRED": "Enter the server address.",
    "DESKTOP_SERVER_URL_SCHEME": "“{{url}}” is not an http or https address.",
    "DESKTOP_SHOWTIME_OUTDATED": "Showtime cannot receive a deck from Portuni. Update Showtime.",
    "DESKTOP_UNSUPPORTED_OS": "This action is available only on macOS.",
    "DESKTOP_URL_REFUSED": "Links of the type “{{scheme}}” are not opened.",
    "DESKTOP_WORKSPACE_DISABLED": "The workspace “{{id}}” is turned off.",
    "DESKTOP_WORKSPACE_EXISTS": "A workspace “{{id}}” already exists.",
    "DESKTOP_WORKSPACE_ID_INVALID": "A workspace ID may contain only lowercase letters, digits and dashes.",
    "DESKTOP_WORKSPACE_LAST": "The last workspace cannot be deleted.",
    "DESKTOP_WORKSPACE_UNKNOWN": "The workspace “{{id}}” does not exist.",
    "DESKTOP_WORKSPACE_WINDOW_OPEN": "Close this workspace's window first.",
    "DEVICE_TOKEN_NOT_FOUND": "The token was not found.",
    "DISCONNECTED": "The connection to the server was lost. Try again.",
    "EDGE_ENDPOINT_NOT_FOUND": "One or both nodes of the relation were not found.",
    "EDGE_NOT_FOUND": "The relation was not found.",
    "EVENT_ALREADY_ARCHIVED": "The event is already archived.",
    "EVENT_NOT_FOUND": "The event was not found.",
    "EXISTS": "A file named “{{filename}}” already exists.",
    "FILE_NOT_FOUND": "The file was not found.",
    "FILE_NOT_ON_DEVICE": "The file is not on this device.",
    "FILE_NO_LOCAL_COPY": "This device has no local copy of the file.",
    "FILE_NO_REMOTE_PATH": "The file is not on the remote, so there is nothing to keep the local version over.",
    "FORBIDDEN": "You do not have permission for this action.",
    "GOOGLE_MODE_ONLY": "Groups are available only with Google sign-in.",
    "HANDOFF_FILE_NOT_HERE": "The handoff file is not on this device yet.",
    "HANDOFF_INVALID": "The sign-in code is not valid or has expired.",
    "HANDOFF_NOT_ALLOWED": "Only a running or suspended thread can be handed off.",
    "HANDOFF_NOT_LOOPBACK": "This sign-in works only on this computer.",
    "HANDOFF_NO_CONTENT": "The thread's content is not on this device yet; try again once it has downloaded.",
    "HANDOFF_NO_MIRROR": "The node has no mirror on this device, so the handoff file cannot be written.",
    "HANDOFF_PATH_INVALID": "The handoff file path is not valid.",
    "HANDOFF_RUN_ELSEWHERE": "The thread is running on the device {{host}}; hand it off there.",
    "HANDOFF_TRANSCRIPT_ELSEWHERE": "The thread's transcript is on the device {{host}}; hand it off there.",
    "HEADLESS_TOKEN_REQUIRES_ADMIN": "Only an administrator can create a token without a user.",
    "HOST_NOT_ALLOWED": "The server refused the request's address.",
    "INSTANCE_DEFAULTS_EFFORT_INVALID": "The effort “{{effort}}” is not valid.",
    "INSTANCE_DEFAULTS_KEY_UNKNOWN": "“{{key}}” is not a known default; only model and effort can be set.",
    "INSTANCE_ENV_KEY_RESERVED": "“{{key}}” cannot be set from an instance.",
    "INSTANCE_ENV_KEY_SECRET": "“{{key}}” looks like a secret. Keep it in the system keychain, not in the instance.",
    "INSTANCE_NOT_FOUND": "The instance was not found.",
    "INTERNAL_ERROR": "Something went wrong on the server (request {{requestId}}).",
    "INVALID_EVENT_DATE": "The event date is not valid.",
    "INVALID_HEALTH": "The health value “{{health}}” is not valid.",
    "INVALID_JSON": "The request could not be read.",
    "INVALID_LOCALE": "That language is not available.",
    "INVALID_PATH": "The file name or path is not valid.",
    "INVALID_REQUEST": "The request was not valid.",
    "INVALID_RESOLVE_ACTION": "This conflict resolution is not valid.",
    "INVALID_SESSION_TRANSITION": "The thread cannot change to that state now.",
    "INVALID_VISIBILITY": "The visibility “{{visibility}}” is not valid.",
    "LIFECYCLE_STATE_INVALID": "This lifecycle state is not valid for the node's type.",
    "LOCAL_MODE_NO_REMOTE": "A personal workspace has no remote; files are shared through a team workspace.",
    "LOGIN_FAILED": "Sign-in failed.",
    "LOGIN_UNAVAILABLE": "Sign-in is not available on this server.",
    "MALFORMED_REQUEST_TARGET": "The request address is not valid.",
    "MCP_CAPACITY_REACHED": "The server has too many open MCP connections. Try again later.",
    "MCP_HOME_NODE_REQUIRED": "A token without a user must connect with a home node.",
    "MCP_RESUME_REFUSED": "This thread cannot be resumed from this connection.",
    "MCP_SCOPE_UNAVAILABLE": "The Portuni database is unreachable, so the connection cannot get its scope.",
    "MCP_SESSION_FORBIDDEN": "This MCP connection belongs to another user.",
    "MCP_SESSION_NOT_FOUND": "The MCP connection has ended. Connect again.",
    "MOVE_REMOTE_MISMATCH": "The node's files are on the remote “{{remoteName}}”, but the new organization uses “{{targetRemote}}”.",
    "MOVE_SOURCE_IS_ORGANIZATION": "An organization cannot be moved under another organization.",
    "MOVE_TARGET_NOT_ORGANIZATION": "A node can be moved only under an organization.",
    "NODE_NOT_FOUND": "The node was not found.",
    "NODE_VISIBILITY_MANAGED": "Visibility is set through sharing, not directly.",
    "NOT_A_DRAFT": "Only a thread that has not started can be deleted.",
    "NOT_EDITABLE": "This file cannot be edited as text.",
    "NOT_FOUND": "The file was not found.",
    "NOT_SERVED_BY_SYNC_AGENT": "The sync agent does not handle this action.",
    "NO_LIVE_RUN": "The thread is not running right now. Try again.",
    "NO_MIRROR": "The node has no mirror on this device.",
    "NO_PENDING_QUESTION": "The question has already been answered or has expired.",
    "NO_PREVIEW": "This .showtime file has no preview. Save it again in the current version of Showtime.",
    "NO_REMOTE": "The node has no remote.",
    "NO_RUNNER_AVAILABLE": "No runner is installed and signed in on this device.",
    "OAUTH_CLIENT_UNVERIFIED": "The client could not be verified: {{reason}}",
    "OAUTH_GOOGLE_LOGIN_FAILED": "Sign-in with Google failed.",
    "OAUTH_GRANT_NOT_FOUND": "The connected app was not found.",
    "OAUTH_INVALID_RESOURCE": "The target resource is not valid.",
    "OAUTH_MISSING_PARAMETER": "The authorization request is missing a required parameter.",
    "OAUTH_PKCE_S256_ONLY": "Only the PKCE S256 method is supported.",
    "OAUTH_REDIRECT_URI_UNREGISTERED": "The redirect address (redirect_uri) is not registered for this client.",
    "OAUTH_SESSION_EXPIRED": "The sign-in session expired or is not valid. Try again.",
    "ORGANIZATION_NOT_FOUND": "The organization was not found.",
    "ORG_ALREADY_ASSIGNED": "The node already belongs to an organization. Remove that relation first.",
    "ORG_LAST_EDGE": "Every node must belong to exactly one organization; this relation cannot be removed.",
    "ORIGIN_NOT_ALLOWED": "The server refused the request's origin.",
    "OWNER_NOT_PERSON": "The owner must be a person with an account.",
    "PATH_IN_USE": "The folder is already the mirror of another node.",
    "PATH_PARAM_REQUIRED": "The file path is missing.",
    "PATH_TRAVERSAL": "The folder must be inside the workspace folder.",
    "PULL_DIRTY_LOCAL": "The file has local changes that are not synced; a pull would overwrite them.",
    "RATE_LIMITED": "Too many requests. Try again in {{retryAfterSeconds}} s.",
    "REQUEST_TIMEOUT": "The server did not answer in time. Try again.",
    "RESPONSIBILITY_NOT_FOUND": "The responsibility was not found.",
    "RESPONSIBILITY_TARGET_INVALID": "Responsibilities can be added only to a project, process or area.",
    "ROUTE_NOT_FOUND": "This action is not available on the server.",
    "RUNNER_REQUIRED": "Choose a runner to start the thread.",
    "RUN_NOT_FOUND": "The run was not found.",
    "SESSION_BIND_REFUSED": "The thread is not running, so the runner cannot connect to it.",
    "SESSION_NOT_DRAFT": "The runner and instance can change only before the thread starts.",
    "SESSION_NOT_FOUND": "The thread was not found.",
    "SESSION_TRANSCRIPT_ELSEWHERE": "The thread's transcript is on the device {{host}}; continue it there.",
    "SYNC_AGENT_DOWN": "The sync agent is not running. Sign in under Settings → Account.",
    "SYNC_JOB_NOT_FOUND": "The sync job was not found.",
    "SYNC_KEY_EMPTY": "The node's sync key must not be empty.",
    "TOOL_NOT_FOUND": "The tool was not found.",
    "TOOL_TARGET_INVALID": "Tools can be added only to a project, process or area.",
    "UNAUTHORIZED": "You are not signed in.",
    "UNKNOWN": "Something went wrong (request {{requestId}}).",
    "UNKNOWN_DETAIL": "Something went wrong: {{detail}}",
    "UNKNOWN_INSTANCE": "The instance was not found.",
    "UNKNOWN_RUNNER": "The runner “{{runner}}” is not known.",
    "USER_EXISTS": "The user {{email}} already exists.",
    "WEBSOCKET_UPGRADE_REQUIRED": "This address only accepts a live connection.",
    "WEBVIEW_PROXY_REQUIRED": "This action is available only in the Portuni app.",
    "WORKSPACE_ROOT_UNSET": "The workspace folder is not set.",
    "WRITE_EXPANSION_REQUIRED": "Writing to this node needs a confirmation first.",
    "WRITE_REFUSED": "You cannot write to this node."
  },
  "files": {
    "banner": {
      "create_mirror": "Create mirror",
      "creating_mirror": "Creating…",
      "error": "Error: {{error}}",
      "no_mirror": "This node has no mirror on this computer – its files are only on the remote so far.",
      "personal_workspace": "Files are stored on this computer only and are not shared. Sharing files needs a team workspace (joining a team).",
      "watcher_errors": "File watching reports an error for this node:" | "File watching reports errors for this node:"
    },
    "form": {
      "cancel": "Cancel"
    },
    "new_file": {
      "button": "New file",
      "create": "Create",
      "creating": "Creating…",
      "menu_item": "New file",
      "more_options": "More options",
      "placeholder": "Name of the new file (e.g. notes.md)",
      "presentation": "New presentation",
      "presentation_title": "Starts a new Showtime presentation in this node's wip/ folder"
    },
    "new_folder": {
      "button": "New folder",
      "create": "Create",
      "placeholder": "Path of the new folder (e.g. wip/archive)"
    },
    "new_task": {
      "button": "New task",
      "title": "Opens an empty thread where you give the agent a task."
    },
    "plan_bar": {
      "apply": "Apply",
      "apply_again": "Apply again",
      "apply_disabled_title": "A new folder appears with the first file you move into it",
      "applying": "Moving <b>{{current}} / {{total}}</b>",
      "applying_button": "Applying",
      "discard": "Discard",
      "failed": "Applying stopped at <b>{{filename}}</b>. <b>{{count}} change</b> remains in the plan." | "Applying stopped at <b>{{filename}}</b>. <b>{{count}} changes</b> remain in the plan.",
      "pending": "<b>{{count}} change</b> waiting to be applied" | "<b>{{count}} changes</b> waiting to be applied"
    },
    "plan_reason": {
      "drag_outside_sections": "Only files in the wip, outputs and resources folders can be moved",
      "file_exists": "The folder already has a file {{name}}",
      "file_gone": "The file no longer exists",
      "folder_exists": "The folder {{name}} already exists",
      "folder_has_untracked": "The folder holds an unregistered file {{name}}",
      "into_itself": "A folder cannot be moved into itself",
      "invalid_folder_name": "Invalid folder name",
      "no_mirror": "Create the node's mirror first",
      "not_a_folder": "This folder cannot be moved",
      "path_empty": "Enter the folder's path",
      "path_needs_name": "Enter a folder name inside the section",
      "path_outside_sections": "The path must start with the wip/, outputs/ or resources/ section",
      "section_move": "A section cannot be moved",
      "section_rename": "A section cannot be renamed",
      "target_outside_sections": "The target must be in the wip, outputs or resources folder",
      "untracked": "The file is not registered yet"
    },
    "remote_watch": {
      "error": "{{remote}}: watching reports an error – {{error}}",
      "retry": "next attempt {{when}}",
      "unwatched": {
        "sweep_error": "{{remote}}: no change watching, the periodic check reports an error – {{error}}",
        "sweep_last": "{{remote}}: no change watching, periodic check only (last {{when}})",
        "sweep_only": "{{remote}}: no change watching, periodic check only"
      },
      "watched": {
        "last_change": "{{remote}} watched, last change {{when}}",
        "last_change_sweep_error": "{{remote}} watched, last change {{when}}; the periodic check reports an error – {{error}}",
        "no_change": "{{remote}} watched, no change yet, checked {{when}}",
        "no_change_sweep_error": "{{remote}} watched, no change yet, checked {{when}}; the periodic check reports an error – {{error}}",
        "not_checked": "{{remote}} watched, not checked yet",
        "not_checked_sweep_error": "{{remote}} watched, not checked yet; the periodic check reports an error – {{error}}"
      }
    },
    "row": {
      "busy": {
        "delete": "deleting",
        "keep_local": "uploading",
        "move": "moving",
        "rename": "renaming",
        "restore": "restoring",
        "take_remote": "downloading"
      },
      "copy_drive_link": "Copy Drive link",
      "copy_path": "Copy the file path",
      "delete": "Delete",
      "delete_confirm": "Really delete?",
      "delete_confirm_title": "Deletes the file from the remote too",
      "drive_link_none": "The file is not on Drive yet",
      "keep_local": "Keep local",
      "keep_local_title": "Push the local version to the remote",
      "not_editable": "This file cannot be edited",
      "open_in_editor": "Open in the editor",
      "open_on_disk": "Show on disk",
      "open_presentation": "Open the presentation preview",
      "plan_badge": {
        "error": "error",
        "error_title": "The move failed",
        "move": "move",
        "move_title": "The move is waiting to be applied"
      },
      "rename": "Rename",
      "restore": "Restore",
      "restore_title": "Pull it from the remote again",
      "take_remote": "Take from remote",
      "take_remote_title": "Overwrite the local copy with the remote version",
      "untracked": "unregistered",
      "untracked_title": "The file is on disk but not registered yet. It is registered on the next sync."
    },
    "sample": {
      "message": "Files of the node {{nodeName}}."
    },
    "sync_bar": {
      "check_on_remote": "Check on the remote",
      "check_remote": "Check the remote",
      "conflicts": "{{count}} conflict" | "{{count}} conflicts",
      "conflicts_title": "Conflict: pick a version on the file (Keep local / Take from remote).",
      "deleted_local": "{{count}} deleted locally" | "{{count}} deleted locally",
      "deleted_local_title": "Deleted locally: Restore pulls a copy again, Delete removes the file everywhere.",
      "error": "Error: {{error}}",
      "hide": "Hide",
      "hide_label": "Hide the sync result",
      "pending_repair": "Unfinished ({{op}}): {{error}}",
      "running": "Syncing...",
      "sync_files": "Sync files",
      "sync_pending": "Sync ({{count}} file to sync)" | "Sync ({{count}} files to sync)"
    },
    "sync_class": {
      "clean": "synced",
      "conflict": "conflict",
      "deleted_local": "missing",
      "native": "native",
      "pull": "pull",
      "push": "push",
      "remote_error": "remote unavailable",
      "remote_missing": "missing on remote"
    },
    "sync_overview": {
      "all_synced": "Everything is synced.",
      "count": {
        "conflict": "Conflict — needs a decision",
        "deleted_local": "Deleted locally — needs a decision",
        "pull": "New on the remote — to pull",
        "push": "To push",
        "remote_missing": "Missing on the remote",
        "untracked": "Unregistered"
      },
      "decide": "Decide",
      "decide_title": "A sync run does not resolve conflicts — open the node and decide",
      "decisions": "<count>{{count}}</count> to decide" | "<count>{{count}}</count> to decide",
      "decisions_title": "Conflicts and locally deleted files. A sync run never touches them by design — open the node and decide.",
      "go_to_node": "Go to the node",
      "node_done": "Synced",
      "node_failed": "Failed",
      "pull_nodes": "<count>{{count}}</count> node with updates from the remote" | "<count>{{count}}</count> nodes with updates from the remote",
      "pull_nodes_title": "Nodes where the remote watcher registered a newer version than this computer has. A sync run pulls them.",
      "sync_all": "Sync all",
      "sync_node": "Sync",
      "title": "Not synced",
      "to_sync": "<count>{{count}}</count> file to sync" | "<count>{{count}}</count> files to sync"
    },
    "sync_run": {
      "adopted": "{{count}} registered" | "{{count}} registered",
      "adopted_remote": "{{count}} new from the remote" | "{{count}} new from the remote",
      "all_synced": "All synced",
      "conflicts": "{{count}} conflict" | "{{count}} conflicts",
      "deleted_local": "{{count}} deleted locally" | "{{count}} deleted locally",
      "deleted_on_remote": "{{count}} deleted on the remote" | "{{count}} deleted on the remote",
      "deleted_remote": "{{count}} cleaned up" | "{{count}} cleaned up",
      "errors": "{{count}} error" | "{{count}} errors",
      "pending_repairs": "{{count}} unfinished" | "{{count}} unfinished",
      "pulled": "{{count}} pulled" | "{{count}} pulled",
      "pushed": "{{count}} pushed" | "{{count}} pushed",
      "repaired": "{{count}} repaired" | "{{count}} repaired",
      "sweep_errors": "remote check failed ({{count}})" | "remote check failed ({{count}})"
    },
    "sync_section": {
      "central": "File sync to Google Drive is managed by the central server <server>{{server}}</server>.",
      "heading": "Sync",
      "more_errors": "… and {{count}} more." | "… and {{count}} more.",
      "personal": "This is a personal workspace – files are stored on this computer only and are not shared. Sharing files needs a team workspace (joining a team).",
      "watcher_errors_nodes": "File watching reports {{count}} error in {{nodes}} nodes." | "File watching reports {{count}} errors in {{nodes}} nodes.",
      "watcher_errors_one_node": "File watching reports {{count}} error in 1 node." | "File watching reports {{count}} errors in 1 node."
    },
    "tree": {
      "collapse": "Collapse",
      "expand": "Expand",
      "folder_sync": {
        "clean": "All synced",
        "conflict": "Conflict inside",
        "pending": "Files waiting to sync",
        "remote_missing": "Some files are missing on the remote"
      },
      "new_subfolder": "New subfolder",
      "rename_folder": "Rename",
      "section_desc": {
        "outputs": "outputs",
        "resources": "resources",
        "wip": "in progress"
      },
      "virtual_folder_tag": "new",
      "virtual_folder_title": "The folder exists only in the plan so far. It is created once it holds a file after applying."
    }
  },
  "graph": {
    "empty": {
      "body": "Portuni maps what you work on: teams, projects, processes. Start by adding your organization.",
      "create_disabled": "Creating nodes requires a higher role",
      "create_organization": "Create organization",
      "title": "Start by creating your first organization."
    },
    "layout": {
      "full_relayout": {
        "aria_label": "Regenerate layout",
        "title": "Regenerate the whole layout, including where organizations are placed"
      },
      "retile": {
        "aria_label": "Arrange nodes",
        "title": "Arrange nodes within organizations (organizations stay in place)"
      }
    },
    "sample": {
      "message": "Graph of {{workspaceName}}."
    }
  },
  "node": {
    "access": {
      "chip": {
        "remove": "Remove"
      },
      "confirm": {
        "cancel": "Cancel",
        "clear_override": "This node's own sharing will be removed and the node will inherit sharing from its parent node again (or be unrestricted if no parent node restricts sharing).",
        "confirm": "Confirm",
        "last_entry": "Removing the last recipient ends the sharing and the node becomes private.",
        "switch": "Switching removes access for {{count}} recipient." | "Switching removes access for {{count}} recipients."
      },
      "inherited": {
        "heading": {
          "area": "Inherits sharing from the area {{sourceName}}",
          "organization": "Inherits sharing from the organization {{sourceName}}",
          "parent": "Inherits sharing from the parent node",
          "principle": "Inherits sharing from the principle {{sourceName}}",
          "process": "Inherits sharing from the process {{sourceName}}",
          "project": "Inherits sharing from the project {{sourceName}}",
          "untyped": "Inherits sharing from {{sourceName}}"
        },
        "set_own": "Set own sharing for this node"
      },
      "load_error": "Could not load sharing.",
      "loading": "Loading…",
      "mode": {
        "aria_label": "Restriction mode",
        "private": {
          "description": "The node is completely invisible to others.",
          "label": "Hidden from others",
          "readonly": "Mode: <value>Hidden from others</value>",
          "summary": "Group · hidden from others"
        },
        "request": {
          "description": "Others can see that the node exists and can ask for access.",
          "label": "On request (others see the name and can ask for access)",
          "readonly": "Mode: <value>On request</value>",
          "summary": "Group · on request"
        }
      },
      "own": {
        "add": "Add a group or user…",
        "cancel": "Cancel",
        "clear": "Remove own sharing and inherit from the organization",
        "empty_error": "Add at least one recipient.",
        "heading": "This node's own sharing",
        "peek_hint": "Replaces the sharing inherited from the organization. Applies only to this node and the nodes below it.",
        "save": "Save",
        "unsaved_hint": "Not saved yet – group sharing is saved with the first recipient. With no recipients, only admins can see the node."
      },
      "picker": {
        "no_match": "Nothing matches.",
        "search_placeholder": "Search…"
      },
      "requests": {
        "heading": "Access requests ({{count}})" | "Access requests ({{count}})"
      },
      "save_error": "Saving failed. Try again.",
      "status": {
        "saved": "Saved",
        "saving": "Saving…"
      },
      "visibility": {
        "aria_label": "Sharing",
        "group": {
          "label": "Group"
        },
        "legend": "Everyone = the whole team · Private = only the author and admins · Group = selected people and groups",
        "private": {
          "description": "Only the creator and admins can see it.",
          "label": "Private"
        },
        "team": {
          "description": "Everyone who is signed in can see it.",
          "disabled_inherited": "This node inherits a restriction from a parent node. It cannot be opened to everyone, only given its own sharing.",
          "label": "Everyone"
        }
      }
    },
    "detail": {
      "actor": {
        "automation": "Automation",
        "automation_placeholder": "Automation (placeholder)",
        "placeholder_name": "{{name}} (placeholder)"
      },
      "archive": {
        "button": "Archive this node",
        "hint": "The node will be hidden from the graph, but its relations and events stay in the database for audit."
      },
      "assignee_picker": {
        "empty": "No other actors to assign.",
        "loading": "Loading…"
      },
      "attribute": {
        "data_source": {
          "add": "Add data source",
          "delete": "Delete data source",
          "edit": "Edit data source",
          "new_title": "New data source"
        },
        "description_placeholder": "Description (optional)",
        "empty": "No entries.",
        "link_placeholder": "Link (optional)",
        "link_placeholder_example": "Link (optional, e.g. https://…)",
        "name_placeholder": "Name",
        "tool": {
          "add": "Add tool",
          "delete": "Delete tool",
          "edit": "Edit tool",
          "new_title": "New tool"
        }
      },
      "connections": {
        "add": "Add relation",
        "cancel_edit": "Cancel",
        "change_relation": "Change relation type",
        "empty": "No relations yet.",
        "flip_direction": "Reverse direction",
        "new_title": "New relation",
        "remove": "Remove relation",
        "restricted": "Access on request",
        "save_relation": "Save relation type",
        "submit": "Add relation",
        "submitting": "Adding…"
      },
      "description": {
        "edit_title": "Edit description",
        "empty": "Not filled in",
        "placeholder": "Describe what this node represents…"
      },
      "error": {
        "create_file_failed": "Couldn't create the file: {{error}}",
        "delete_failed": "Delete failed: {{error}}",
        "presentation_failed": "Couldn't create the presentation: {{error}}",
        "remote_delete_repair": "Couldn't delete the file from the remote. The local copy and its record were kept.",
        "rename_failed": "Rename failed: {{error}}"
      },
      "events": {
        "empty": "No events yet."
      },
      "files": {
        "empty": "No files yet."
      },
      "form": {
        "cancel": "Cancel",
        "close": "Close",
        "create": "Create",
        "creating": "Creating…",
        "save": "Save",
        "save_changes": "Save changes",
        "saving": "Saving…"
      },
      "goal": {
        "edit_title": "Edit goal",
        "empty": "Not filled in",
        "placeholder": "Why this node exists and what it should achieve…"
      },
      "header": {
        "copy_id_title": "Click to copy the ID",
        "copy_path_title": "{{path}}\nClick to copy the path",
        "create_mirror": "Create mirror",
        "creating_mirror": "Creating…",
        "open_in_finder": "Open folder in Finder",
        "remote": {
          "copy_link_drive": "Copy link to Google Drive",
          "copy_link_generic": "Copy link to the remote",
          "copy_link_named": "Copy link to {{remoteName}}",
          "open_drive": "Open on Google Drive",
          "open_generic": "Open on the remote",
          "open_named": "Open on {{remoteName}}"
        }
      },
      "health": {
        "change_title": "Change project health"
      },
      "lifecycle": {
        "change_title": "Change lifecycle state",
        "unset_badge": "not set",
        "unset_option": "— not set —"
      },
      "loading": "Loading…",
      "meta": {
        "toggle": "Meta"
      },
      "node_picker": {
        "empty": "No results",
        "placeholder": "Select a node…",
        "search_placeholder": "Search…"
      },
      "organization": {
        "empty": "No organizations available.",
        "none": "— No organization —"
      },
      "owner": {
        "empty": "No actors available.",
        "loading": "Loading actors…",
        "no_match": "Nothing matches “{{query}}”.",
        "none": "— None —",
        "none_option": "— None —",
        "search_placeholder": "Search actors…"
      },
      "pane": {
        "back": "Back",
        "close": "Close detail",
        "collapse": "Hide detail",
        "edit": "Edit",
        "edit_title": "Edit node"
      },
      "responsibilities": {
        "add": "Add responsibility",
        "assign": "assign",
        "assignees_label": "Assignees",
        "delete": "Delete responsibility",
        "description_placeholder": "Description (optional)",
        "edit": "Edit responsibility",
        "empty": "No responsibilities yet.",
        "loading_actors": "Loading…",
        "move_down": "Move down",
        "move_up": "Move up",
        "new_title": "New responsibility",
        "no_assignees": "— Nobody yet",
        "registry_empty": "The actor registry is empty.",
        "title_placeholder": "Responsibility name",
        "unassign": "Remove"
      },
      "section": {
        "danger_zone": "Danger zone",
        "data_sources": "Data sources",
        "description": "Description",
        "goal": "Goal",
        "organization": "Organization",
        "owner": "Owner",
        "responsibilities": "Responsibilities",
        "tools": "Tools"
      },
      "sync_dot": {
        "clean": "Everything synced",
        "conflict": "Conflicts in files",
        "pending": "Files are waiting to sync",
        "remote_missing": "Some files are missing on the remote"
      },
      "tab": {
        "connections": "Relations",
        "events": "Events",
        "files": "Files",
        "overview": "Overview",
        "sessions": "Threads",
        "sharing": "Sharing"
      }
    },
    "events": {
      "add": {
        "content_placeholder": "What happened?",
        "failed": "Couldn't add the event: {{error}}",
        "heading": "New event",
        "open": "Add event",
        "submit": "Add event",
        "submitting": "Adding…"
      },
      "card": {
        "archive": "Archive",
        "archive_failed": "Couldn't archive the event: {{error}}",
        "cancel": "Cancel",
        "edit": "Edit",
        "mark_resolved": "Mark as resolved",
        "resolve_failed": "Couldn't mark the event as resolved: {{error}}",
        "resolved_badge": "resolved",
        "save": "Save",
        "save_failed": "Couldn't save the event: {{error}}",
        "saving": "Saving…"
      }
    },
    "sample": {
      "message": "Details of the node {{nodeName}}."
    },
    "sessions": {
      "handoffs": {
        "continue": "Continue from handoff",
        "continuing": "Continuing…",
        "heading": "Handoffs to continue from",
        "view": "View handoff"
      },
      "list": {
        "empty": "No threads yet.",
        "loading": "Loading threads…",
        "show_archived": "Show archived"
      },
      "resume": {
        "continues_conversation": "the next message continues the conversation",
        "handoff_changed": "(handoff edited since it was suspended)",
        "handoff_uncheckable": "(the handoff can't be checked on this device)",
        "server_suspended": {
          "boot_sweep": "(suspended by the server, server restart)",
          "disconnect": "(suspended by the server, disconnected)",
          "handoff": "(suspended by the server, handed off to another device)",
          "host_lost": "(suspended by the server, the process was orphaned after a restart)",
          "idle": "(suspended by the server, inactive for 30 min)",
          "no_reason": "(suspended by the server)",
          "suspend_timeout": "(suspended by the server, the agent didn't finish the handoff in time)",
          "terminal_exit": "(suspended by the server, terminal closed)"
        },
        "starts_from_summary": "the next message starts it from the summary"
      },
      "row": {
        "cancel_rename": "Cancel",
        "close": "Close",
        "open_chat": "Open chat",
        "rename": "Rename",
        "runner_unknown": "unknown",
        "save_name": "Save name",
        "view_handoff": "View handoff",
        "write_scope": "Write: {{writeCount}}",
        "write_scope_title": "Number of nodes in this thread's write scope"
      }
    }
  },
  "server": {
    "handoff": {
      "footer": "The conversation was not saved; continue from this summary.",
      "heading": {
        "files": "## Changed files",
        "messages": "## Recent messages",
        "question": "## Open question",
        "read_scope": "## Read scope",
        "write_scope": "## Write scope"
      },
      "last_active_line": "Last activity: {{when}} UTC",
      "message_agent": "- **Agent:** {{text}}",
      "message_user": "- **User:** {{text}}",
      "node_line": "Node: {{nodeName}}",
      "node_line_none": "Node: (none)",
      "none": {
        "files": "(none)",
        "messages": "(none)",
        "question": "(none)",
        "read_scope": "(none)",
        "write_scope": "(none)"
      }
    },
    "oauth": {
      "consent": {
        "allow": "Allow",
        "deny": "Deny",
        "loopback_warning": "This app is asking to sign in for a local (loopback) address <strong>{{host}}</strong>, which usually means an app running on this computer.",
        "redirect_notice": "Once you allow it, the app will be redirected to:",
        "requests_access": "<span class=\"client\">{{clientName}}</span> is asking for access to your Portuni account.",
        "title": "Portuni – access request"
      },
      "error": {
        "title": "Portuni – sign-in error"
      }
    },
    "sample": {
      "message": "Hello, {{userName}}."
    },
    "session": {
      "default_draft_name": "New task"
    }
  },
  "settings": {
    "access_requests": {
      "list": {
        "approve": "Approve",
        "approving": "…",
        "deny": "Deny",
        "resolve_failed": "Resolving the request failed. Try again."
      },
      "panel": {
        "description": "Pending requests for access to nodes in the “On request” mode. Approving adds the requester to the node's sharing recipients (for an inherited restriction, to the parent node's).",
        "empty": "No pending requests.",
        "loading": "Loading requests…",
        "retry": "Try again",
        "title": "Access requests"
      },
      "request": {
        "already_visible": "You already have access – refresh the detail",
        "button": "Request access",
        "cancel_title": "Cancel",
        "message_placeholder": "Message (optional)",
        "send_failed": "Sending failed.",
        "send_title": "Send request",
        "sent": "Request sent"
      }
    },
    "account": {
      "connected_apps": {
        "columns": {
          "app": "App",
          "connected": "Connected",
          "last_used": "Last used"
        },
        "disconnect": {
          "button": "Disconnect",
          "confirm": "Disconnect the app “{{appName}}”? It will have to sign in again.",
          "title": "Disconnect app"
        },
        "empty": "No connected apps yet. Add Portuni as a connector in claude.ai or in Claude Code and sign in with Google.",
        "loading": "Loading connected apps…",
        "retry": "Try again",
        "title": "Connected apps"
      },
      "error_box": {
        "dismiss": "Close"
      },
      "intro": "Sign-in to the central Portuni server with Google OAuth.",
      "language": {
        "description": "The language of Portuni's interface. Saved to your account, so it applies on all your devices.",
        "label": "Language",
        "options": {
          "cs": "Čeština",
          "en": "English",
          "pseudo": "Pseudo"
        },
        "select_aria_label": "Interface language"
      },
      "loading": "Checking sign-in status…",
      "not_configured": {
        "body": "Add <code>server_url</code> and <code>google_client_id</code> to the config file:",
        "title": "The central server is not configured."
      },
      "not_desktop": "Available only in the desktop app.",
      "sign_in": {
        "busy": "Signing in…",
        "button": "Sign in with Google"
      },
      "title": "Account",
      "tokens": {
        "cancel": "Cancel",
        "columns": {
          "created": "Created",
          "expires": "Expires",
          "last_used": "Last used",
          "name": "Name",
          "status": "Status"
        },
        "create": "Create",
        "created": {
          "close": "Close",
          "copied": "Copied",
          "copy": "Copy",
          "title": "Token created",
          "warning": "The token is shown only once. Copy it and keep it somewhere safe."
        },
        "creating": "Creating…",
        "empty": "No device tokens yet.",
        "label_placeholder": "Token name (e.g. dev-laptop)",
        "loading": "Loading tokens…",
        "new_token": "New token",
        "retry": "Try again",
        "revoke": {
          "button": "Revoke",
          "confirm": "Revoke the token “{{tokenLabel}}”? This cannot be undone.",
          "title": "Revoke token"
        },
        "status": {
          "active": "active",
          "revoked": "revoked"
        },
        "title": "Device tokens"
      },
      "user": {
        "role": "Role:",
        "sign_out": "Sign out"
      },
      "workspace_kind": {
        "label": "Workspace type:",
        "personal": "personal",
        "team": "team"
      }
    },
    "actors": {
      "modal": {
        "cancel": "Cancel",
        "create": "Create",
        "name_label": "Name",
        "name_placeholder_automation": "Daily CRM report",
        "name_placeholder_person": "Jane Doe",
        "name_required": "Name is required.",
        "notes_label": "Notes",
        "notes_placeholder": "Internal notes…",
        "placeholder_automation": "An automation cannot be a placeholder.",
        "placeholder_checkbox": "Stand-in person (to be replaced by a real one)",
        "placeholder_label": "Placeholder",
        "save_changes": "Save changes",
        "saving": "Saving…",
        "title_create": "New actor",
        "title_edit": "Edit actor",
        "type_automation": "Automation",
        "type_label": "Type",
        "type_locked": "The type cannot be changed after creation.",
        "type_person": "Person",
        "user_label": "User account",
        "user_none": "— Not linked —",
        "user_unknown": "{{userId}} (unknown)",
        "users_empty": "No registered users available.",
        "users_load_failed": "Could not load users: {{error}}",
        "users_loading": "Loading users…"
      },
      "page": {
        "add": "Add actor",
        "delete": "Delete",
        "edit": "Edit",
        "empty_filtered": "No actors match the filters.",
        "empty_none": "No actors yet. Add the first one.",
        "loading": "Loading actors…",
        "search_label": "Search actors",
        "search_placeholder": "Search actors…",
        "title": "Actors"
      },
      "placeholder_filter": {
        "all": "All",
        "placeholder": "Placeholders",
        "real": "Real"
      },
      "status": {
        "automation": "Automation",
        "placeholder": "Placeholder",
        "real_person": "Real person",
        "registered_user": "Registered user"
      },
      "table": {
        "actions": "Actions",
        "name": "Name",
        "notes": "Notes",
        "status": "Status",
        "type": "Type"
      },
      "type_badge": {
        "automation": "Automation",
        "person": "Person"
      },
      "type_filter": {
        "all": "All",
        "automation": "Automations",
        "person": "People"
      }
    },
    "mcp": {
      "actions": {
        "install_claude": "Add to Claude Code (~/.claude.json)",
        "install_codex": "Add to Codex (~/.codex/config.toml)",
        "install_vibe": "Add to Vibe (~/.vibe/config.toml)",
        "regenerate": "Generate new token"
      },
      "browser_only_note": "The actions above only work in the desktop app; they are disabled in browser dev mode.",
      "central_note": {
        "with_url": "Front door on this device: graph tools are proxied to <mono>{{serverUrl}}</mono>, file and folder tools run on this device. The token belongs to the front door on this device; the device token for the central server is managed in the Account section.",
        "without_url": "Front door on this device: graph tools are proxied to the central server, file and folder tools run on this device. The token belongs to the front door on this device; the device token for the central server is managed in the Account section."
      },
      "env_hint": {
        "body": "{{agent}} reads the bearer token from an environment variable — it won't use a token in config.toml. Add this line to the end of <code>~/.zshrc</code> (or your shell rc) and open a new terminal:",
        "copy_export": "Copy export",
        "dismiss": "Hide",
        "export_copied": "Export line copied to clipboard",
        "loading_token": "Loading token…",
        "written": "Written to {{path}}"
      },
      "fields": {
        "copy_token": "Copy token",
        "copy_url": "Copy URL",
        "hide_token": "Hide token",
        "no_auth": "(server without auth)",
        "show_token": "Show token",
        "token": "Token",
        "url": "URL"
      },
      "flash": {
        "copy_failed": "Copying failed: {{error}}",
        "install_desktop_only": "Installing the configuration only works from the desktop app.",
        "install_failed": "Error: {{error}}",
        "install_written": "Written to {{path}}",
        "regenerate_desktop_only": "Token rotation is only available from the desktop app.",
        "regenerate_failed": "Error: {{error}}",
        "regenerated": "New token generated. Remember to run the install again for Claude Code, Codex and Vibe.",
        "token_copied": "Token copied to clipboard",
        "token_desktop_only": "The token is only available in the desktop app.",
        "token_load_failed": "Could not load the token: {{error}}",
        "url_copied": "URL copied to clipboard"
      },
      "intro": "The endpoint Claude Code, Codex and Mistral Vibe connect to. The token lives in the macOS Keychain and survives app restarts.",
      "status": {
        "loading": "Checking server status…",
        "no_port": "the active workspace has no MCP port assigned",
        "unavailable": "MCP server is unavailable: <mono>{{reason}}</mono>"
      },
      "title": "MCP server"
    },
    "page": {
      "actors_loading": "Loading actors…",
      "autosave": "Changes are saved automatically.",
      "integrations": {
        "showtime": {
          "description": "A <code>.showtime</code> file opens as a presentation preview (the preview Showtime writes into the file on every save). When Showtime is installed, the preview offers “Open in Showtime”: the deck opens in Showtime, and the agent Showtime starts gets a connection to Portuni with this node as its home node and the node's mirror as a second working folder.",
          "desktop_only": "Opening in Showtime is only available in the desktop app.",
          "found": "Showtime.app found.",
          "label": "Showtime",
          "not_found": "Showtime.app not found (looked in /Applications and ~/Applications).",
          "searching": "Looking for Showtime.app…"
        },
        "title": "Integrations"
      },
      "loading": "Loading…",
      "tabs": {
        "access_requests": "Access requests",
        "account": "Account",
        "actors": "Actors",
        "general": "General",
        "runners": "Runners",
        "sync": "Sync",
        "users": "Users",
        "workspaces": "Workspaces"
      },
      "title": "Settings"
    },
    "runners": {
      "create": {
        "env_label": "Environment variables (one per line, KEY=value)",
        "env_placeholder": "CLAUDE_CONFIG_DIR=/Users/you/.claude-work",
        "name_label": "Name",
        "name_placeholder": "E.g. Work",
        "name_required": "Enter an instance name.",
        "runner_label": "Runner",
        "runner_required": "Enter a runner (e.g. claude).",
        "submit": "Create instance",
        "submitting": "Creating…",
        "title": "Add instance"
      },
      "detected": {
        "badge_ready": "ready",
        "badge_unavailable": "unavailable",
        "empty": "No runner is registered on this device yet.",
        "intro": "A runner is a tool (e.g. Claude Code) that the server starts and drives over the canonical event protocol. Sign-in stays with the CLI itself; Portuni never offers its own sign-in.",
        "loading": "Detecting available runners…",
        "not_installed": "Not installed on this device.",
        "not_signed_in": "Installed but not signed in; sign in directly in the {{runner}} CLI.",
        "title": "Runners"
      },
      "env_keys": {
        "portuni_key": "“{{key}}”: PORTUNI_* variables cannot be set from the instance registry.",
        "secret_shaped": "“{{key}}” looks like a secret (*_TOKEN/*_KEY/*_SECRET/*PASSWORD*); store it in the OS keychain, not here."
      },
      "instances": {
        "dismiss_error": "Close",
        "empty": "No instances yet.",
        "intro": "An instance describes what goes into the environment of a started task, typically <code>CLAUDE_CONFIG_DIR=…</code> to switch accounts. For security reasons, values are never read back from the registry.",
        "loading": "Loading instances…",
        "retry": "Try again",
        "title": "Instances"
      },
      "org_defaults": {
        "intro": "When a task is created from a node, the instance set for its organization is offered as the default.",
        "none": "(none)",
        "select_aria_label": "Default instance for {{orgName}}",
        "title": "Default instance per organization"
      },
      "row": {
        "cancel_delete": "Cancel",
        "cancel_edit": "Cancel",
        "confirm_delete": "Delete for good",
        "delete": "Delete",
        "delete_confirm_message": "The instance is deleted from the registry and is no longer offered when creating a task. Organization defaults that pointed to it are cleared.",
        "edit": "Edit",
        "env_key_set": "{{key}} (set)",
        "env_label": "Environment variables (one per line, KEY=value)",
        "env_placeholder": "CLAUDE_CONFIG_DIR=/Users/you/.claude-work",
        "env_summary": "variables: {{keys}}",
        "env_values_hint": "For security reasons, values are never read back. An empty value on an existing key stays unchanged; enter it again only if you want to overwrite it.",
        "name_label": "Name",
        "name_required": "The instance name is required.",
        "no_env": "(no env)",
        "runner_label": "Runner",
        "save": "Save",
        "saving": "Saving…"
      }
    },
    "sample": {
      "message": "Settings of {{workspaceName}}."
    },
    "update": {
      "check_now": "Check now",
      "desktop_only": "Updates are only available in the desktop app.",
      "install": "Download and install",
      "last_checked": "Last checked: {{when}}",
      "restart": "Restart",
      "status": {
        "available": "{{version}} is available.",
        "checking": "Checking for updates…",
        "downloading": "Downloading and installing…",
        "downloading_pct": "Downloading and installing ({{pct}} %)",
        "not_checked": "Not checked yet.",
        "ready": "Update installed – restart to finish.",
        "up_to_date": "You have the latest version."
      },
      "title": "Updates",
      "version": "Version {{version}}",
      "whats_new": "What's new"
    },
    "users": {
      "columns": {
        "email": "Email",
        "last_sign_in": "Last sign-in",
        "name": "Name",
        "role": "Role"
      },
      "description": "Accounts with access to this Portuni server. Invited users have never signed in yet – you can share with and assign a placeholder account right away.",
      "empty": "No users yet.",
      "invite": {
        "invalid_email": "Enter a valid email.",
        "placeholder": "email@example.com",
        "submit": "Invite",
        "submitting": "Inviting…",
        "user_exists": "The user already exists"
      },
      "invited_badge": "Invited",
      "loading": "Loading users…",
      "none": "—",
      "retry": "Try again",
      "title": "Users"
    },
    "workspaces": {
      "create": {
        "created_hint": "Workspace created. Enter the Turso token after you switch to the workspace, in Settings.",
        "google_client_id_label": "Google Client ID",
        "google_client_secret_label": "Google Client Secret",
        "id_hint": "ID: <mono>{{id}}</mono> – cannot be changed after creation.",
        "id_hint_invalid": "ID: <mono>(invalid)</mono> – cannot be changed after creation.",
        "invalid_name": "Enter a valid workspace name.",
        "kind_aria_label": "Workspace type",
        "kind_label": "Workspace type",
        "kind_personal": "Personal workspace",
        "kind_team": "Team workspace",
        "name_label": "Name",
        "name_placeholder": "e.g. Personal",
        "server_url_label": "Server URL",
        "submit": "Create workspace",
        "submit_busy": "Creating…",
        "title": "Add workspace",
        "turso_url_hint": "If you leave it empty, the workspace starts with a local SQLite database – the token is entered after you switch to the workspace, in Settings.",
        "turso_url_label": "Turso URL (optional)",
        "workspace_root_label": "Workspace root"
      },
      "list": {
        "badge_active": "active",
        "badge_window_open": "window open",
        "cancel_delete": "Cancel",
        "col_id": "ID",
        "col_kind": "Type",
        "col_name": "Name",
        "col_port": "Port",
        "col_status": "Status",
        "confirm_delete": "Really delete",
        "delete": "Delete",
        "delete_warning": "The workspace is removed from the app, its sidecar stops and its tokens are deleted from the Keychain. Data on disk (mirror folders and databases) stays – delete it by hand if you don't want it.",
        "disable": "Disable",
        "dismiss_error": "Close",
        "empty": "No workspaces yet.",
        "enable": "Enable",
        "intro": "Each workspace has its own sidecar, port and data (a personal workspace has its own Turso database, a team workspace a central server). The health of a workspace without an open window can only be seen here – backend status events only reach that workspace's own window.",
        "kind_personal": "personal",
        "kind_team": "team",
        "loading": "Loading workspaces…",
        "open": "Open",
        "restart": "Restart",
        "retry": "Try again",
        "status_awaiting_sign_in": "waiting for sign-in",
        "status_disabled": "disabled",
        "status_running": "running",
        "status_stopped": "not running",
        "switch_to_window": "Switch to window",
        "title": "Workspaces"
      }
    }
  }
}
