// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "chat": {
    "event": {
      "denied": {
        "connector_disabled": "This connector is turned off for the run. The agent should use the Portuni server.",
        "denied_by_user": "You declined.",
        "not_answered": "The question was not answered.",
        "run_ended": "The run ended before an answer arrived.",
        "turn_stopped": "The turn was stopped before an answer arrived.",
        "write_no_path": "The {{tool}} call has no {{field}}, so the write could not be checked.",
        "write_outside_mirror": "Writing to {{path}} was blocked: it is outside this node's mirror.",
        "write_outside_root": "Writing to {{path}} was blocked: it is outside the Portuni folder."
      },
      "error": {
        "browser_sign_in_declined": "{{server}} asked for a sign-in in a browser. The chat cannot open one, so the request was declined.",
        "provider_failed": "The run ended with a provider error ({{subtype}}).",
        "provider_not_logged_in": "Claude Code is not signed in on this device."
      },
      "question": {
        "agent_question": {
          "title": "Question from the agent"
        },
        "mcp_confirmation": {
          "title": "Confirm for {{server}}"
        },
        "plan_approval": {
          "title": "Approve the plan?"
        },
        "scope_expand": {
          "detail": "The agent wants to read a node outside this thread's current scope.",
          "title": "Expand the thread's scope?"
        }
      }
    },
    "model": {
      "description": {
        "balanced": "Balanced model for everyday work.",
        "fastest": "The fastest and cheapest model.",
        "most_capable": "The most capable model, slower and more expensive."
      }
    },
    "sample": {
      "message": "Thread with {{runnerName}}."
    }
  },
  "common": {
    "app": {
      "editor_guard": {
        "back_to_editor": "Back to editor",
        "description": "The file in the editor has unsaved changes. Do you want to save them?",
        "description_quit": "The file in the editor has unsaved changes. Do you want to save them before closing the app?",
        "discard": "Discard changes",
        "save": "Save",
        "saving": "Saving…",
        "title": "Unsaved changes"
      },
      "graph_error": {
        "hint": "Is the Portuni server running on port 4011?",
        "title": "Couldn't load the graph"
      },
      "graph_loading": "Loading graph…",
      "thread_error": {
        "handoff_failed": "Couldn't hand off the thread: {{error}}",
        "load_failed": "Couldn't load the node's threads: {{error}}",
        "rename_failed": "Couldn't rename the thread: {{error}}"
      }
    },
    "create_node": {
      "cancel": "Cancel",
      "field": {
        "description": "Description",
        "name": "Name",
        "organization": "Organization",
        "type": "Type"
      },
      "hint": {
        "first_organization": "You're starting by creating your first organization, so the type is preset.",
        "name_min_length": "The name must be at least {{count}} character long." | "The name must be at least {{count}} characters long."
      },
      "no_organizations": "Create an organization first, then come back here.",
      "placeholder": {
        "description": "Short description (optional)",
        "name_default": "Client onboarding",
        "name_organization": "Acme Inc."
      },
      "submit": "Create",
      "submitting": "Creating…",
      "title": "New node"
    },
    "date_picker": {
      "next_month": "Next month",
      "previous_month": "Previous month"
    },
    "editor": {
      "back": "Back",
      "back_title": "Back to details",
      "close_title": "Close editor",
      "codemirror": {
        "all": "all",
        "by_word": "by word",
        "close": "close",
        "completions": "Completions",
        "control_character": "Control character",
        "current_match": "current match",
        "diagnostics": "Diagnostics",
        "find": "Find",
        "fold_line": "Fold line",
        "folded_code": "folded code",
        "folded_lines": "Folded lines",
        "go": "go",
        "go_to_line": "Go to line",
        "match_case": "match case",
        "next": "next",
        "no_diagnostics": "No diagnostics",
        "on_line": "on line",
        "previous": "previous",
        "regexp": "regexp",
        "replace": "replace",
        "replace_all": "replace all",
        "replace_field": "Replace",
        "replaced_match_on_line": "replaced match on line $",
        "replaced_matches": "replaced $ matches",
        "selection_deleted": "Selection deleted",
        "to": "to",
        "unfold": "unfold",
        "unfold_line": "Unfold line",
        "unfolded_lines": "Unfolded lines"
      },
      "collapse_title": "Shrink to panel",
      "conflict": {
        "keep_mine": "Keep mine",
        "message": "The file changed on disk in the meantime.",
        "reload_theirs": "Load theirs"
      },
      "expand_title": "Full window",
      "external_change": {
        "message": "The file changed on disk.",
        "reload": "Load the current version"
      },
      "html_preview": {
        "copied": "Copied",
        "copy_path": "Copy path",
        "copy_path_title": "Copy the file path",
        "deck_without_node": "The deck doesn't belong to any node.",
        "frame_title_html": "HTML preview",
        "frame_title_showtime": "Presentation preview",
        "open_in_browser": "Open in browser",
        "open_in_showtime": "Open in Showtime",
        "open_in_showtime_title": "Open the deck in the Showtime app with the node's context"
      },
      "loading": "Loading…",
      "mode": {
        "edit": "Edit",
        "group_label": "Editor mode",
        "preview": "Preview"
      },
      "save": "Save",
      "save_title": "Save (Cmd/Ctrl+S)",
      "saving": "Saving…"
    },
    "error_boundary": {
      "retry": "Try rendering again",
      "title": "Portuni hit an error while rendering. Copy the text below and switch back to a working agent."
    },
    "error_overlay": {
      "dismiss": "Hide",
      "title": "Portuni hit an error (this panel replaces a blank white screen). Copy the text below."
    },
    "footer": {
      "mcp": {
        "label_down": "mcp ×",
        "label_loading": "mcp…",
        "label_running": "mcp",
        "title_down": "MCP server unavailable: {{reason}}",
        "title_loading": "Checking the MCP server…",
        "title_running": "MCP server is running: {{url}}"
      },
      "pull": {
        "label": "{{count}} node on the remote" | "{{count}} nodes on the remote",
        "title": "The remote watcher found newer versions of files. Open the sync overview."
      },
      "threads": {
        "label": "{{count}} thread" | "{{count}} threads",
        "title": "Active threads: {{runningCount}}"
      },
      "unsynced": {
        "label": "↑ {{pendingCount}} unsynced",
        "title": "Unsynced: {{count}} file" | "Unsynced: {{count}} files"
      },
      "update": {
        "available_label": "↑ {{version}}",
        "available_title": "New Portuni version – click to update",
        "ready_label": "Restart",
        "ready_title": "Restart to finish the update"
      }
    },
    "gate": {
      "central_login": {
        "not_configured": "This is a team workspace, but its configuration is missing. Add <code>server_url</code> and <code>google_client_id</code> to <code>config.json</code>.",
        "prompt": "Sign in with Google to access the shared graph.",
        "submit": "Sign in with Google",
        "submitting": "Signing in…",
        "title": "Portuni"
      },
      "first_steps": {
        "confirm": "Got it, open Portuni",
        "description": "You'll see the shared graph right away; what you can see in it is governed by permissions on the server.",
        "mirrors": "Mirrors on your Mac are created node by node: open a node in the graph and click <label>New task</label> or the folder icon in the node's header. Portuni creates the node's local folder and pulls its files. Without this step, the content stays only on the server.",
        "title": "You're signed in"
      },
      "setup": {
        "join_team": {
          "description": "Your organization already runs a Portuni server. Enter its address, then sign in with your Google account.",
          "error_empty_url": "The server address can't be empty.",
          "submit": "Connect",
          "submitting": "Connecting…",
          "title": "Join a team",
          "url_placeholder": "api.your-company.com"
        },
        "personal": {
          "description": "Only on this Mac, no account. Good for trying Portuni out.",
          "submit": "Create personal workspace",
          "title": "Personal workspace"
        },
        "subtitle": "How do you want to start?",
        "title": "Welcome to Portuni"
      },
      "turso": {
        "description": "Portuni connects to a remote Turso database. Paste the auth token; we'll store it in the macOS Keychain and restart the backend.",
        "error_empty_token": "The token can't be empty.",
        "submit": "Save and restart",
        "submitting": "Saving…",
        "title": "Connect to Turso",
        "token_placeholder": "eyJhbGciOiJFZERTQSIs…"
      },
      "workspace_migration": {
        "description": "Portuni now supports multiple workspaces. Your existing data moves under the name you choose, and the name can't be changed afterwards.",
        "id_invalid": "ID: (invalid)",
        "id_preview": "ID: {{id}}",
        "submit": "Continue",
        "submitting": "Migrating…",
        "title": "Name your workspace"
      }
    },
    "node_list": {
      "activity": {
        "running": "A task is running",
        "waiting": "A task is waiting for an answer"
      },
      "empty_nodes": "No open nodes. Open a node with Search nodes (⌘K) or create a new one.",
      "empty_tasks": "No tasks. Start a task from a node's detail with the New task button.",
      "group": {
        "done": "Done",
        "draft": "New",
        "running": "Working",
        "suspended": "Suspended",
        "waiting": "Need attention"
      },
      "heading": "Open",
      "mode": {
        "aria_label": "Arrangement",
        "nodes": "Nodes",
        "nodes_title": "Group by node",
        "state": "Status",
        "state_title": "Tasks only, by status"
      },
      "node": {
        "close": "Close node",
        "new_task_aria_label": "New task",
        "new_task_title": "New task for this node"
      },
      "task": {
        "close": "Close thread",
        "handoff": "Hand off to another device",
        "state": {
          "done": "Done",
          "draft": "New",
          "running": "Running",
          "suspended": "Suspended",
          "waiting": "Waiting for an answer"
        }
      }
    },
    "node_type": {
      "area": "Area",
      "organization": "Organization",
      "principle": "Principle",
      "process": "Process",
      "project": "Project"
    },
    "overview": {
      "activity": {
        "empty": "No activity yet.",
        "session_write": "{{sessionName}} wrote to {{nodeName}}",
        "title": "Recent activity"
      },
      "attention": {
        "access_request": "Access request: {{userName}}",
        "empty": "Nothing needs attention.",
        "sync_issue": "Sync problem: {{nodeName}}",
        "title": "Needs attention"
      },
      "counter": {
        "attention": "Needs attention",
        "running": "Running",
        "unsynced": "Not synced",
        "waiting": "Waiting on me"
      },
      "loading": "Loading the overview…",
      "new_nodes": {
        "empty": "No recently created nodes.",
        "title": "New nodes"
      },
      "refresh": "Refresh",
      "show_all": "Show {{count}}" | "Show all {{count}}",
      "threads": {
        "cli": "Plus {{count}} CLI session ({{running}} running)" | "Plus {{count}} CLI sessions ({{running}} running)",
        "empty": "No running or suspended threads.",
        "no_node": "Chat",
        "no_reason": "no reason given",
        "review_queue": "Review queue (disconnected jumps)",
        "title": "Threads"
      },
      "title": "Overview"
    },
    "palette": {
      "description": "Type a node name and press Enter.",
      "empty": "No nodes",
      "footer": {
        "close": "Close",
        "navigate": "Navigate",
        "open": "Open"
      },
      "key": {
        "enter": "Enter",
        "esc": "Esc"
      },
      "placeholder": "Search nodes…",
      "title": "Search nodes"
    },
    "quit_guard": {
      "cancel": "Cancel",
      "close_without_sync": "Close without syncing",
      "description": "You have {{count}} file that isn't on the remote (unsynced). If you close the app, it stays only on this device." | "You have {{count}} files that aren't on the remote (unsynced). If you close the app, they stay only on this device.",
      "show_and_sync": "Show and sync",
      "title": "Unsynced work"
    },
    "sample": {
      "items": "{{count}} item" | "{{count}} items",
      "link": "Open <link>settings</link>.",
      "message": "Welcome to Portuni, {{userName}}."
    },
    "sidebar": {
      "brand": "Portuni",
      "create": {
        "button": "New node",
        "denied": "Creating nodes requires a higher role",
        "title_graph": "Create a new node (organization, project, process, area, principle)",
        "title_work": "Creates a new node and opens it in Work"
      },
      "filters": {
        "node_types": "Node types",
        "organizations": "Organizations",
        "relation_types": "Relation types",
        "status": "Status",
        "status_value": {
          "active": "Active",
          "archived": "Archived",
          "completed": "Completed"
        },
        "summary": "Overview",
        "summary_nodes": "Nodes",
        "summary_relations": "Relations"
      },
      "footer": {
        "graph": "Click a node to open its detail. Drag to pan, scroll to zoom.",
        "settings": "Changes are saved automatically."
      },
      "hint": {
        "overview": "A summary of the whole workspace: running threads, nodes that need attention, recent activity and newly created nodes.",
        "settings": "Portuni configuration: the agent command for launching from nodes and the MCP server parameters for Claude Code and Codex."
      },
      "search": {
        "button": "Search nodes…",
        "title": "Search nodes ({{shortcut}})"
      },
      "settings": "Settings",
      "theme": {
        "to_dark": "Switch to dark mode",
        "to_light": "Switch to light mode"
      },
      "view": {
        "graph": "Graph",
        "group_label": "View",
        "overview": "Overview",
        "work": "Work"
      },
      "workspace_switcher": {
        "aria_label": "Workspace",
        "hint": {
          "disabled": "disabled",
          "open": "open",
          "this_window": "this window",
          "unavailable": "unavailable"
        },
        "manage": "Manage workspaces…",
        "placeholder": "Workspace",
        "title": "Open another workspace"
      }
    },
    "thread": {
      "composer": {
        "placeholder": {
          "archived": "This thread is archived.",
          "open": "Write a message…"
        }
      },
      "state": {
        "header": {
          "archived": "Archived",
          "closed": "Closed",
          "draft": "New",
          "running": "Running",
          "suspended": "Suspended"
        },
        "row": {
          "archived": "Archived",
          "closed": "Done",
          "draft": "New",
          "running": "Running",
          "suspended": "Suspended"
        },
        "waiting": "Waiting on me"
      }
    },
    "ui": {
      "command": {
        "description": "Search for a command to run…",
        "title": "Command palette"
      },
      "dialog": {
        "close_button": "Close",
        "close_label": "Close"
      },
      "spinner": {
        "loading": "Loading"
      }
    },
    "workspace": {
      "empty": {
        "description": "Open any node and work on it. You can have several nodes open and switch between them.",
        "search_placeholder": "Search nodes…",
        "title": "Open a node in Work"
      },
      "pick_node_hint": "Select a node on the left.",
      "show_node_detail": "Show node detail"
    }
  },
  "desktop": {
    "sample": {
      "message": "Portuni for {{userName}}."
    }
  },
  "errors": {
    "ACCESS_ALREADY_VISIBLE": "You already have access.",
    "ACCESS_DUPLICATE_ENTRIES": "Someone is in the access list twice.",
    "ACCESS_GROUP_NEEDS_ENTRIES": "Group visibility needs at least one person or group.",
    "ACCESS_REQUEST_NOT_FOUND": "The access request was not found.",
    "ACCESS_REQUEST_PENDING": "Your access request is already waiting.",
    "ACCESS_REQUEST_RESOLVED": "The access request has already been resolved.",
    "ACCESS_UNKNOWN_USERS": "{{count}} user in the access list does not exist." | "{{count}} users in the access list do not exist.",
    "BEARER_MISMATCH": "Your sign-in is no longer valid. Sign in again.",
    "BEARER_MISSING": "You are not signed in.",
    "BODY_TOO_LARGE": "The request is too large.",
    "CENTRAL_UNREACHABLE": "The central server is unreachable.",
    "CONFIRMATION_REQUIRED": "The action needs a confirmation.",
    "CONFLICT": "The file changed since you opened it.",
    "CONSTRAINT_VIOLATION": "The change conflicts with existing data.",
    "DATA_SOURCE_NOT_FOUND": "The data source was not found.",
    "DATA_SOURCE_TARGET_INVALID": "Data sources can be added only to a project, process or area.",
    "DESKTOP_CONFIG_UNAVAILABLE": "The server has no sign-in settings for the desktop app.",
    "DEVICE_TOKEN_NOT_FOUND": "The token was not found.",
    "DISCONNECTED": "The connection to the server was lost. Try again.",
    "EDGE_ENDPOINT_NOT_FOUND": "One or both nodes of the relation were not found.",
    "EDGE_NOT_FOUND": "The relation was not found.",
    "EVENT_ALREADY_ARCHIVED": "The event is already archived.",
    "EVENT_NOT_FOUND": "The event was not found.",
    "EXISTS": "A file named “{{filename}}” already exists.",
    "FILE_NOT_FOUND": "The file was not found.",
    "FILE_NOT_ON_DEVICE": "The file is not on this device.",
    "FILE_NO_LOCAL_COPY": "This device has no local copy of the file.",
    "FILE_NO_REMOTE_PATH": "The file is not on the remote, so there is nothing to keep the local version over.",
    "FORBIDDEN": "You do not have permission for this action.",
    "GOOGLE_MODE_ONLY": "Groups are available only with Google sign-in.",
    "HANDOFF_FILE_NOT_HERE": "The handoff file is not on this device yet.",
    "HANDOFF_INVALID": "The sign-in code is not valid or has expired.",
    "HANDOFF_NOT_ALLOWED": "Only a running or suspended thread can be handed off.",
    "HANDOFF_NOT_LOOPBACK": "This sign-in works only on this computer.",
    "HANDOFF_NO_CONTENT": "The thread's content is not on this device yet; try again once it has downloaded.",
    "HANDOFF_NO_MIRROR": "The node has no mirror on this device, so the handoff file cannot be written.",
    "HANDOFF_PATH_INVALID": "The handoff file path is not valid.",
    "HANDOFF_RUN_ELSEWHERE": "The thread is running on the device {{host}}; hand it off there.",
    "HANDOFF_TRANSCRIPT_ELSEWHERE": "The thread's transcript is on the device {{host}}; hand it off there.",
    "HEADLESS_TOKEN_REQUIRES_ADMIN": "Only an administrator can create a token without a user.",
    "HOST_NOT_ALLOWED": "The server refused the request's address.",
    "INSTANCE_DEFAULTS_EFFORT_INVALID": "The effort “{{effort}}” is not valid.",
    "INSTANCE_DEFAULTS_KEY_UNKNOWN": "“{{key}}” is not a known default; only model and effort can be set.",
    "INSTANCE_ENV_KEY_RESERVED": "“{{key}}” cannot be set from an instance.",
    "INSTANCE_ENV_KEY_SECRET": "“{{key}}” looks like a secret. Keep it in the system keychain, not in the instance.",
    "INSTANCE_NOT_FOUND": "The instance was not found.",
    "INTERNAL_ERROR": "Something went wrong on the server (request {{requestId}}).",
    "INVALID_EVENT_DATE": "The event date is not valid.",
    "INVALID_HEALTH": "The health value “{{health}}” is not valid.",
    "INVALID_JSON": "The request could not be read.",
    "INVALID_PATH": "The file name or path is not valid.",
    "INVALID_REQUEST": "The request was not valid.",
    "INVALID_RESOLVE_ACTION": "This conflict resolution is not valid.",
    "INVALID_SESSION_TRANSITION": "The thread cannot change to that state now.",
    "INVALID_VISIBILITY": "The visibility “{{visibility}}” is not valid.",
    "LIFECYCLE_STATE_INVALID": "This lifecycle state is not valid for the node's type.",
    "LOCAL_MODE_NO_REMOTE": "A personal workspace has no remote; files are shared through a team workspace.",
    "LOGIN_FAILED": "Sign-in failed.",
    "LOGIN_UNAVAILABLE": "Sign-in is not available on this server.",
    "MALFORMED_REQUEST_TARGET": "The request address is not valid.",
    "MCP_CAPACITY_REACHED": "The server has too many open MCP connections. Try again later.",
    "MCP_HOME_NODE_REQUIRED": "A token without a user must connect with a home node.",
    "MCP_RESUME_REFUSED": "This thread cannot be resumed from this connection.",
    "MCP_SCOPE_UNAVAILABLE": "The Portuni database is unreachable, so the connection cannot get its scope.",
    "MCP_SESSION_FORBIDDEN": "This MCP connection belongs to another user.",
    "MCP_SESSION_NOT_FOUND": "The MCP connection has ended. Connect again.",
    "MOVE_REMOTE_MISMATCH": "The node's files are on the remote “{{remoteName}}”, but the new organization uses “{{targetRemote}}”.",
    "MOVE_SOURCE_IS_ORGANIZATION": "An organization cannot be moved under another organization.",
    "MOVE_TARGET_NOT_ORGANIZATION": "A node can be moved only under an organization.",
    "NODE_NOT_FOUND": "The node was not found.",
    "NODE_VISIBILITY_MANAGED": "Visibility is set through sharing, not directly.",
    "NOT_A_DRAFT": "Only a thread that has not started can be deleted.",
    "NOT_EDITABLE": "This file cannot be edited as text.",
    "NOT_FOUND": "The file was not found.",
    "NOT_SERVED_BY_SYNC_AGENT": "The sync agent does not handle this action.",
    "NO_LIVE_RUN": "The thread is not running right now. Try again.",
    "NO_MIRROR": "The node has no mirror on this device.",
    "NO_PENDING_QUESTION": "The question has already been answered or has expired.",
    "NO_PREVIEW": "This .showtime file has no preview. Save it again in the current version of Showtime.",
    "NO_REMOTE": "The node has no remote.",
    "NO_RUNNER_AVAILABLE": "No runner is installed and signed in on this device.",
    "OAUTH_CLIENT_UNVERIFIED": "The client could not be verified: {{reason}}",
    "OAUTH_GOOGLE_LOGIN_FAILED": "Sign-in with Google failed.",
    "OAUTH_GRANT_NOT_FOUND": "The connected app was not found.",
    "OAUTH_INVALID_RESOURCE": "The target resource is not valid.",
    "OAUTH_MISSING_PARAMETER": "The authorization request is missing a required parameter.",
    "OAUTH_PKCE_S256_ONLY": "Only the PKCE S256 method is supported.",
    "OAUTH_REDIRECT_URI_UNREGISTERED": "The redirect address (redirect_uri) is not registered for this client.",
    "OAUTH_SESSION_EXPIRED": "The sign-in session expired or is not valid. Try again.",
    "ORGANIZATION_NOT_FOUND": "The organization was not found.",
    "ORG_ALREADY_ASSIGNED": "The node already belongs to an organization. Remove that relation first.",
    "ORG_LAST_EDGE": "Every node must belong to exactly one organization; this relation cannot be removed.",
    "ORIGIN_NOT_ALLOWED": "The server refused the request's origin.",
    "OWNER_NOT_PERSON": "The owner must be a person with an account.",
    "PATH_IN_USE": "The folder is already the mirror of another node.",
    "PATH_PARAM_REQUIRED": "The file path is missing.",
    "PATH_TRAVERSAL": "The folder must be inside the workspace folder.",
    "PULL_DIRTY_LOCAL": "The file has local changes that are not synced; a pull would overwrite them.",
    "RATE_LIMITED": "Too many requests. Try again in {{retryAfterSeconds}} s.",
    "REQUEST_TIMEOUT": "The server did not answer in time. Try again.",
    "RESPONSIBILITY_NOT_FOUND": "The responsibility was not found.",
    "RESPONSIBILITY_TARGET_INVALID": "Responsibilities can be added only to a project, process or area.",
    "ROUTE_NOT_FOUND": "This action is not available on the server.",
    "RUNNER_REQUIRED": "Choose a runner to start the thread.",
    "RUN_NOT_FOUND": "The run was not found.",
    "SESSION_BIND_REFUSED": "The thread is not running, so the runner cannot connect to it.",
    "SESSION_NOT_DRAFT": "The runner and instance can change only before the thread starts.",
    "SESSION_NOT_FOUND": "The thread was not found.",
    "SESSION_TRANSCRIPT_ELSEWHERE": "The thread's transcript is on the device {{host}}; continue it there.",
    "SYNC_AGENT_DOWN": "The sync agent is not running. Sign in under Settings → Account.",
    "SYNC_JOB_NOT_FOUND": "The sync job was not found.",
    "SYNC_KEY_EMPTY": "The node's sync key must not be empty.",
    "TOOL_NOT_FOUND": "The tool was not found.",
    "TOOL_TARGET_INVALID": "Tools can be added only to a project, process or area.",
    "UNAUTHORIZED": "You are not signed in.",
    "UNKNOWN": "Something went wrong (request {{requestId}}).",
    "UNKNOWN_DETAIL": "Something went wrong: {{detail}}",
    "UNKNOWN_INSTANCE": "The instance was not found.",
    "UNKNOWN_RUNNER": "The runner “{{runner}}” is not known.",
    "USER_EXISTS": "The user {{email}} already exists.",
    "WEBSOCKET_UPGRADE_REQUIRED": "This address only accepts a live connection.",
    "WEBVIEW_PROXY_REQUIRED": "This action is available only in the Portuni app.",
    "WORKSPACE_ROOT_UNSET": "The workspace folder is not set.",
    "WRITE_EXPANSION_REQUIRED": "Writing to this node needs a confirmation first.",
    "WRITE_REFUSED": "You cannot write to this node."
  },
  "files": {
    "plan_bar": {
      "failed": "Applying stopped at <b>{{filename}}</b>. <b>{{count}} change</b> remains in the plan." | "Applying stopped at <b>{{filename}}</b>. <b>{{count}} changes</b> remain in the plan.",
      "pending": "<b>{{count}} change</b> waiting to be applied" | "<b>{{count}} changes</b> waiting to be applied"
    },
    "sample": {
      "message": "Files of the node {{nodeName}}."
    },
    "sync_overview": {
      "pull_nodes": "<count>{{count}}</count> node with updates from the remote" | "<count>{{count}}</count> nodes with updates from the remote",
      "to_sync": "<count>{{count}}</count> file to sync" | "<count>{{count}}</count> files to sync"
    }
  },
  "graph": {
    "empty": {
      "body": "Portuni maps what you work on: teams, projects, processes. Start by adding your organization.",
      "create_disabled": "Creating nodes requires a higher role",
      "create_organization": "Create organization",
      "title": "Start by creating your first organization."
    },
    "layout": {
      "full_relayout": {
        "aria_label": "Regenerate layout",
        "title": "Regenerate the whole layout, including where organizations are placed"
      },
      "retile": {
        "aria_label": "Arrange nodes",
        "title": "Arrange nodes within organizations (organizations stay in place)"
      }
    },
    "sample": {
      "message": "Graph of {{workspaceName}}."
    }
  },
  "node": {
    "sample": {
      "message": "Details of the node {{nodeName}}."
    }
  },
  "server": {
    "sample": {
      "message": "Hello, {{userName}}."
    }
  },
  "settings": {
    "sample": {
      "message": "Settings of {{workspaceName}}."
    }
  }
}
