// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "chat": {
    "event": {
      "denied": {
        "connector_disabled": "This connector is turned off for the run. The agent should use the Portuni server.",
        "denied_by_user": "You declined.",
        "not_answered": "The question was not answered.",
        "run_ended": "The run ended before an answer arrived.",
        "turn_stopped": "The turn was stopped before an answer arrived.",
        "write_no_path": "The {{tool}} call has no {{field}}, so the write could not be checked.",
        "write_outside_mirror": "Writing to {{path}} was blocked: it is outside this node's mirror.",
        "write_outside_root": "Writing to {{path}} was blocked: it is outside the Portuni folder."
      },
      "error": {
        "browser_sign_in_declined": "{{server}} asked for a sign-in in a browser. The chat cannot open one, so the request was declined.",
        "provider_failed": "The run ended with a provider error ({{subtype}}).",
        "provider_not_logged_in": "Claude Code is not signed in on this device."
      },
      "question": {
        "agent_question": {
          "title": "Question from the agent"
        },
        "mcp_confirmation": {
          "title": "Confirm for {{server}}"
        },
        "plan_approval": {
          "title": "Approve the plan?"
        },
        "scope_expand": {
          "detail": "The agent wants to read a node outside this thread's current scope.",
          "title": "Expand the thread's scope?"
        }
      }
    },
    "model": {
      "description": {
        "balanced": "Balanced model for everyday work.",
        "fastest": "The fastest and cheapest model.",
        "most_capable": "The most capable model, slower and more expensive."
      }
    },
    "sample": {
      "message": "Thread with {{runnerName}}."
    }
  },
  "common": {
    "sample": {
      "items": "{{count}} item" | "{{count}} items",
      "link": "Open <link>settings</link>.",
      "message": "Welcome to Portuni, {{userName}}."
    }
  },
  "desktop": {
    "sample": {
      "message": "Portuni for {{userName}}."
    }
  },
  "errors": {
    "ACCESS_ALREADY_VISIBLE": "You already have access.",
    "ACCESS_DUPLICATE_ENTRIES": "Someone is in the access list twice.",
    "ACCESS_GROUP_NEEDS_ENTRIES": "Group visibility needs at least one person or group.",
    "ACCESS_REQUEST_NOT_FOUND": "The access request was not found.",
    "ACCESS_REQUEST_PENDING": "Your access request is already waiting.",
    "ACCESS_REQUEST_RESOLVED": "The access request has already been resolved.",
    "ACCESS_UNKNOWN_USERS": "{{count}} user in the access list does not exist." | "{{count}} users in the access list do not exist.",
    "BEARER_MISMATCH": "Your sign-in is no longer valid. Sign in again.",
    "BEARER_MISSING": "You are not signed in.",
    "BODY_TOO_LARGE": "The request is too large.",
    "CENTRAL_UNREACHABLE": "The central server is unreachable.",
    "CONFIRMATION_REQUIRED": "The action needs a confirmation.",
    "CONFLICT": "The file changed since you opened it.",
    "CONSTRAINT_VIOLATION": "The change conflicts with existing data.",
    "DATA_SOURCE_NOT_FOUND": "The data source was not found.",
    "DATA_SOURCE_TARGET_INVALID": "Data sources can be added only to a project, process or area.",
    "DESKTOP_CONFIG_UNAVAILABLE": "The server has no sign-in settings for the desktop app.",
    "DEVICE_TOKEN_NOT_FOUND": "The token was not found.",
    "DISCONNECTED": "The connection to the server was lost. Try again.",
    "EDGE_ENDPOINT_NOT_FOUND": "One or both nodes of the relation were not found.",
    "EDGE_NOT_FOUND": "The relation was not found.",
    "EVENT_ALREADY_ARCHIVED": "The event is already archived.",
    "EVENT_NOT_FOUND": "The event was not found.",
    "EXISTS": "A file named “{{filename}}” already exists.",
    "FILE_NOT_FOUND": "The file was not found.",
    "FILE_NOT_ON_DEVICE": "The file is not on this device.",
    "FILE_NO_LOCAL_COPY": "This device has no local copy of the file.",
    "FILE_NO_REMOTE_PATH": "The file is not on the remote, so there is nothing to keep the local version over.",
    "FORBIDDEN": "You do not have permission for this action.",
    "GOOGLE_MODE_ONLY": "Groups are available only with Google sign-in.",
    "HANDOFF_FILE_NOT_HERE": "The handoff file is not on this device yet.",
    "HANDOFF_INVALID": "The sign-in code is not valid or has expired.",
    "HANDOFF_NOT_ALLOWED": "Only a running or suspended thread can be handed off.",
    "HANDOFF_NOT_LOOPBACK": "This sign-in works only on this computer.",
    "HANDOFF_NO_CONTENT": "The thread's content is not on this device yet; try again once it has downloaded.",
    "HANDOFF_NO_MIRROR": "The node has no mirror on this device, so the handoff file cannot be written.",
    "HANDOFF_PATH_INVALID": "The handoff file path is not valid.",
    "HANDOFF_RUN_ELSEWHERE": "The thread is running on the device {{host}}; hand it off there.",
    "HANDOFF_TRANSCRIPT_ELSEWHERE": "The thread's transcript is on the device {{host}}; hand it off there.",
    "HEADLESS_TOKEN_REQUIRES_ADMIN": "Only an administrator can create a token without a user.",
    "HOST_NOT_ALLOWED": "The server refused the request's address.",
    "INSTANCE_DEFAULTS_EFFORT_INVALID": "The effort “{{effort}}” is not valid.",
    "INSTANCE_DEFAULTS_KEY_UNKNOWN": "“{{key}}” is not a known default; only model and effort can be set.",
    "INSTANCE_ENV_KEY_RESERVED": "“{{key}}” cannot be set from an instance.",
    "INSTANCE_ENV_KEY_SECRET": "“{{key}}” looks like a secret. Keep it in the system keychain, not in the instance.",
    "INSTANCE_NOT_FOUND": "The instance was not found.",
    "INTERNAL_ERROR": "Something went wrong on the server (request {{requestId}}).",
    "INVALID_EVENT_DATE": "The event date is not valid.",
    "INVALID_HEALTH": "The health value “{{health}}” is not valid.",
    "INVALID_JSON": "The request could not be read.",
    "INVALID_PATH": "The file name or path is not valid.",
    "INVALID_REQUEST": "The request was not valid.",
    "INVALID_RESOLVE_ACTION": "This conflict resolution is not valid.",
    "INVALID_SESSION_TRANSITION": "The thread cannot change to that state now.",
    "INVALID_VISIBILITY": "The visibility “{{visibility}}” is not valid.",
    "LIFECYCLE_STATE_INVALID": "This lifecycle state is not valid for the node's type.",
    "LOCAL_MODE_NO_REMOTE": "A personal workspace has no remote; files are shared through a team workspace.",
    "LOGIN_FAILED": "Sign-in failed.",
    "LOGIN_UNAVAILABLE": "Sign-in is not available on this server.",
    "MALFORMED_REQUEST_TARGET": "The request address is not valid.",
    "MCP_CAPACITY_REACHED": "The server has too many open MCP connections. Try again later.",
    "MCP_HOME_NODE_REQUIRED": "A token without a user must connect with a home node.",
    "MCP_RESUME_REFUSED": "This thread cannot be resumed from this connection.",
    "MCP_SCOPE_UNAVAILABLE": "The Portuni database is unreachable, so the connection cannot get its scope.",
    "MCP_SESSION_FORBIDDEN": "This MCP connection belongs to another user.",
    "MCP_SESSION_NOT_FOUND": "The MCP connection has ended. Connect again.",
    "MOVE_REMOTE_MISMATCH": "The node's files are on the remote “{{remoteName}}”, but the new organization uses “{{targetRemote}}”.",
    "MOVE_SOURCE_IS_ORGANIZATION": "An organization cannot be moved under another organization.",
    "MOVE_TARGET_NOT_ORGANIZATION": "A node can be moved only under an organization.",
    "NODE_NOT_FOUND": "The node was not found.",
    "NODE_VISIBILITY_MANAGED": "Visibility is set through sharing, not directly.",
    "NOT_A_DRAFT": "Only a thread that has not started can be deleted.",
    "NOT_EDITABLE": "This file cannot be edited as text.",
    "NOT_FOUND": "The file was not found.",
    "NOT_SERVED_BY_SYNC_AGENT": "The sync agent does not handle this action.",
    "NO_LIVE_RUN": "The thread is not running right now. Try again.",
    "NO_MIRROR": "The node has no mirror on this device.",
    "NO_PENDING_QUESTION": "The question has already been answered or has expired.",
    "NO_PREVIEW": "This .showtime file has no preview. Save it again in the current version of Showtime.",
    "NO_REMOTE": "The node has no remote.",
    "NO_RUNNER_AVAILABLE": "No runner is installed and signed in on this device.",
    "OAUTH_CLIENT_UNVERIFIED": "The client could not be verified: {{reason}}",
    "OAUTH_GOOGLE_LOGIN_FAILED": "Sign-in with Google failed.",
    "OAUTH_GRANT_NOT_FOUND": "The connected app was not found.",
    "OAUTH_INVALID_RESOURCE": "The target resource is not valid.",
    "OAUTH_MISSING_PARAMETER": "The authorization request is missing a required parameter.",
    "OAUTH_PKCE_S256_ONLY": "Only the PKCE S256 method is supported.",
    "OAUTH_REDIRECT_URI_UNREGISTERED": "The redirect address (redirect_uri) is not registered for this client.",
    "OAUTH_SESSION_EXPIRED": "The sign-in session expired or is not valid. Try again.",
    "ORGANIZATION_NOT_FOUND": "The organization was not found.",
    "ORG_ALREADY_ASSIGNED": "The node already belongs to an organization. Remove that relation first.",
    "ORG_LAST_EDGE": "Every node must belong to exactly one organization; this relation cannot be removed.",
    "ORIGIN_NOT_ALLOWED": "The server refused the request's origin.",
    "OWNER_NOT_PERSON": "The owner must be a person with an account.",
    "PATH_IN_USE": "The folder is already the mirror of another node.",
    "PATH_PARAM_REQUIRED": "The file path is missing.",
    "PATH_TRAVERSAL": "The folder must be inside the workspace folder.",
    "PULL_DIRTY_LOCAL": "The file has local changes that are not synced; a pull would overwrite them.",
    "RATE_LIMITED": "Too many requests. Try again in {{retryAfterSeconds}} s.",
    "REQUEST_TIMEOUT": "The server did not answer in time. Try again.",
    "RESPONSIBILITY_NOT_FOUND": "The responsibility was not found.",
    "RESPONSIBILITY_TARGET_INVALID": "Responsibilities can be added only to a project, process or area.",
    "ROUTE_NOT_FOUND": "This action is not available on the server.",
    "RUNNER_REQUIRED": "Choose a runner to start the thread.",
    "RUN_NOT_FOUND": "The run was not found.",
    "SESSION_BIND_REFUSED": "The thread is not running, so the runner cannot connect to it.",
    "SESSION_NOT_DRAFT": "The runner and instance can change only before the thread starts.",
    "SESSION_NOT_FOUND": "The thread was not found.",
    "SESSION_TRANSCRIPT_ELSEWHERE": "The thread's transcript is on the device {{host}}; continue it there.",
    "SYNC_AGENT_DOWN": "The sync agent is not running. Sign in under Settings → Account.",
    "SYNC_JOB_NOT_FOUND": "The sync job was not found.",
    "SYNC_KEY_EMPTY": "The node's sync key must not be empty.",
    "TOOL_NOT_FOUND": "The tool was not found.",
    "TOOL_TARGET_INVALID": "Tools can be added only to a project, process or area.",
    "UNAUTHORIZED": "You are not signed in.",
    "UNKNOWN": "Something went wrong (request {{requestId}}).",
    "UNKNOWN_DETAIL": "Something went wrong: {{detail}}",
    "UNKNOWN_INSTANCE": "The instance was not found.",
    "UNKNOWN_RUNNER": "The runner “{{runner}}” is not known.",
    "USER_EXISTS": "The user {{email}} already exists.",
    "WEBSOCKET_UPGRADE_REQUIRED": "This address only accepts a live connection.",
    "WEBVIEW_PROXY_REQUIRED": "This action is available only in the Portuni app.",
    "WORKSPACE_ROOT_UNSET": "The workspace folder is not set.",
    "WRITE_EXPANSION_REQUIRED": "Writing to this node needs a confirmation first.",
    "WRITE_REFUSED": "You cannot write to this node."
  },
  "files": {
    "sample": {
      "message": "Files of the node {{nodeName}}."
    }
  },
  "graph": {
    "sample": {
      "message": "Graph of {{workspaceName}}."
    }
  },
  "node": {
    "sample": {
      "message": "Details of the node {{nodeName}}."
    }
  },
  "server": {
    "sample": {
      "message": "Hello, {{userName}}."
    }
  },
  "settings": {
    "sample": {
      "message": "Settings of {{workspaceName}}."
    }
  }
}
