// portuni:// MCP resources (#255): reading any of these on the bundled
// sidecar used to fail with ENOENT /$bunfs/root/*.md, because the runtime
// read a live .md file next to the module via import.meta.url -- a path
// `bun build --compile` never bundles since nothing statically imports it.
// The bodies are now compiled-in string constants (resources-text.ts,
// generated by scripts/gen-mcp-resources.mjs), so this drives the real MCP
// server end to end (list + read every resource) to catch a regression to
// runtime file reads, and separately checks the generated constants have
// not drifted from their .md sources (a forgotten regeneration after
// editing a .md file).

import { describe, it, before, after } from "node:test";
import assert from "node:assert/strict";
import { readFile, readdir, mkdtemp, rm } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";
import { createClient as createDbClient, type Client as DbClient } from "@libsql/client";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { ensureSchemaOn } from "../apps/server/infra/schema.js";
import { setDbForTesting } from "../apps/server/infra/db.js";
import { resetLocalDbForTests } from "../apps/server/domain/sync/local-db.js";
import { createMcpServer, buildDefaultEnvIdentity } from "../apps/server/mcp/server.js";
import * as generated from "../apps/server/mcp/resources/resources-text.js";

const RESOURCE_URIS = [
  "portuni://architecture",
  "portuni://sync-model",
  "portuni://scope-rules",
  "portuni://enums",
];

let workspace: string;
let db: DbClient;
let mcpClient: Client;

before(async () => {
  workspace = await mkdtemp(join(tmpdir(), "portuni-mcp-resources-"));
  process.env.PORTUNI_WORKSPACE_ROOT = workspace;
  resetLocalDbForTests();

  db = createDbClient({ url: ":memory:" });
  await ensureSchemaOn(db);
  setDbForTesting(db);

  const { server } = createMcpServer(buildDefaultEnvIdentity());
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  mcpClient = new Client(
    { name: "portuni-resources-test-client", version: "0.0.1" },
    { capabilities: {} },
  );
  await server.connect(serverTransport);
  await mcpClient.connect(clientTransport);
});

after(async () => {
  await mcpClient.close();
  setDbForTesting(null);
  resetLocalDbForTests();
  await rm(workspace, { recursive: true, force: true });
});

describe("portuni:// MCP resources", () => {
  it("listResources returns exactly the four documented resources", async () => {
    const { resources } = await mcpClient.listResources();
    const uris = resources.map((r) => r.uri).sort();
    assert.deepEqual(uris, [...RESOURCE_URIS].sort());
  });

  for (const uri of RESOURCE_URIS) {
    it(`readResource(${uri}) returns non-empty markdown text`, async () => {
      const result = await mcpClient.readResource({ uri });
      assert.equal(result.contents.length, 1);
      const content = result.contents[0] as { mimeType?: string; text?: string };
      assert.equal(content.mimeType, "text/markdown");
      assert.ok(typeof content.text === "string" && content.text.length > 0);
    });
  }

  it("the generated resources-text.ts constants match their .md sources (no stale regeneration)", async () => {
    const resourcesDir = join(
      dirname(fileURLToPath(import.meta.url)),
      "../apps/server/mcp/resources",
    );
    const mdFiles = (await readdir(resourcesDir)).filter((f) => f.endsWith(".md"));
    assert.ok(mdFiles.length > 0, "expected at least one .md source file");
    for (const file of mdFiles) {
      const constName =
        file
          .slice(0, -".md".length)
          .toUpperCase()
          .replace(/-/g, "_") + "_MD";
      const generatedValue = (generated as Record<string, string>)[constName];
      assert.ok(
        typeof generatedValue === "string",
        `expected resources-text.ts to export ${constName} for ${file}`,
      );
      const source = await readFile(join(resourcesDir, file), "utf8");
      assert.equal(
        generatedValue,
        source,
        `${constName} is stale -- run \`npm run gen:resources\` after editing ${file}`,
      );
    }
  });
});
