// Postgres cutover, batch B5 -- counterpart of db-export.ts. Reads the JSON
// export back into an EMPTY Postgres/PGlite target that already has the
// baseline schema applied (ensureSchemaOn -- see docs/runbooks/
// postgres-cutover.md for the full sequence). Refuses outright if any
// table already has rows: a partial re-import silently duplicating or
// half-overwriting live data is worse than an import that has to be told
// to start over.
//
// Insert order is db-export.ts's own TABLE_ORDER (topological / FK-safe).
// One exception: session_runs.resumed_from_run_id is the schema's only
// self-referencing FK, so a row can reference another row of the SAME
// table not yet inserted even in a correct row order (ULID order is
// chronological in practice, but not a guarantee). Inserted as NULL, then
// backfilled in a second pass once every session_runs row exists.

import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { DbClient, DbRow, InValue } from "./db.js";
import { TABLE_ORDER } from "./db-export.js";
import { SOLO_USER } from "./schema.js";

const IMPORT_BATCH = 500;
const SELF_REFERENCING_FK: Readonly<Record<string, string>> = {
  session_runs: "resumed_from_run_id",
};

// "Empty" means "only what ensureSchemaOn itself put there" -- applying the
// baseline to a fresh target always seeds exactly one users row (the solo
// user, apps/server/infra/schema.ts's seedSoloUser), unconditionally,
// regardless of auth mode. That row is expected on every legitimate import
// target and must not trip the non-empty guard; anything else in `users`,
// or ANY row in any other table, means real data already landed here.
async function assertTargetEmpty(db: DbClient): Promise<void> {
  for (const table of TABLE_ORDER) {
    const sql =
      table === "users" ? `SELECT COUNT(*) AS c FROM users WHERE id != ?` : `SELECT COUNT(*) AS c FROM ${table}`;
    const res = await db.execute(table === "users" ? { sql, args: [SOLO_USER] } : sql);
    const count = Number(res.rows[0]?.c ?? 0);
    if (count > 0) {
      throw new Error(
        `db-import: target table "${table}" already has ${count} row(s) -- refusing to import into a non-empty database`,
      );
    }
  }
}

async function readTableRows(inDir: string, table: string): Promise<DbRow[]> {
  try {
    const raw = await readFile(join(inDir, `${table}.json`), "utf8");
    return JSON.parse(raw) as DbRow[];
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw err;
  }
}

async function insertRows(db: DbClient, table: string, rows: DbRow[]): Promise<void> {
  if (rows.length === 0) return;
  const deferredColumn = SELF_REFERENCING_FK[table];
  const allColumns = Object.keys(rows[0]);
  const insertColumns = deferredColumn ? allColumns.filter((c) => c !== deferredColumn) : allColumns;
  const placeholders = insertColumns.map(() => "?").join(", ");
  // `users` is the one table assertTargetEmpty tolerates a pre-existing row
  // in (the solo user seeded by the baseline apply, see its own comment) --
  // upsert there so the source's real row (if it happens to share that
  // same well-known id) replaces the placeholder instead of colliding with
  // it. Every other table is genuinely empty at this point, so a plain
  // INSERT is correct and cheaper.
  const conflictClause =
    table === "users"
      ? ` ON CONFLICT (id) DO UPDATE SET ${insertColumns
          .filter((c) => c !== "id")
          .map((c) => `${c} = excluded.${c}`)
          .join(", ")}`
      : "";
  const stmts = rows.map((row) => ({
    sql: `INSERT INTO ${table} (${insertColumns.join(", ")}) VALUES (${placeholders})${conflictClause}`,
    args: insertColumns.map((c) => row[c] as InValue),
  }));
  for (let i = 0; i < stmts.length; i += IMPORT_BATCH) {
    await db.batch(stmts.slice(i, i + IMPORT_BATCH), "write");
  }

  if (!deferredColumn) return;
  const backfill = rows.filter((r) => r[deferredColumn] !== null && r[deferredColumn] !== undefined);
  for (let i = 0; i < backfill.length; i += IMPORT_BATCH) {
    const chunk = backfill.slice(i, i + IMPORT_BATCH);
    await db.batch(
      chunk.map((row) => ({
        sql: `UPDATE ${table} SET ${deferredColumn} = ? WHERE id = ?`,
        args: [row[deferredColumn] as InValue, row.id as InValue],
      })),
      "write",
    );
  }
}

// Postgres's GENERATED BY DEFAULT AS IDENTITY (remote_routing.id) keeps its
// own sequence separate from any explicit values an INSERT supplies -- the
// next auto-assigned id would collide with (or fall behind) whatever was
// just imported unless the sequence is fast-forwarded past the highest
// imported id. SQLite's AUTOINCREMENT has no such step: it always looks at
// the actual max rowid. A no-op on libsql (no sequence to resync) and on
// an empty table (nothing to resync past).
async function resyncIdentitySequence(db: DbClient, table: string, column: string): Promise<void> {
  if (db.dialect !== "postgres") return;
  await db.execute(
    `SELECT setval(pg_get_serial_sequence('${table}', '${column}'), COALESCE((SELECT MAX(${column}) FROM ${table}), 1), (SELECT MAX(${column}) FROM ${table}) IS NOT NULL)`,
  );
}

export interface ImportResult {
  tables: Record<string, number>;
}

export async function importDb(db: DbClient, inDir: string): Promise<ImportResult> {
  await assertTargetEmpty(db);

  const tables: Record<string, number> = {};
  for (const table of TABLE_ORDER) {
    const rows = await readTableRows(inDir, table);
    tables[table] = rows.length;
    await insertRows(db, table, rows);
  }
  await resyncIdentitySequence(db, "remote_routing", "id");
  return { tables };
}
