import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import {
  ARCHITECTURE_MD,
  SYNC_MODEL_MD,
  SCOPE_RULES_MD,
  ENUMS_MD,
} from "./resources-text.js";

interface ResourceDef {
  name: string;
  uri: string;
  text: string;
  title: string;
  description: string;
}

const RESOURCES: readonly ResourceDef[] = [
  {
    name: "architecture",
    uri: "portuni://architecture",
    text: ARCHITECTURE_MD,
    title: "Portuni architecture",
    description:
      "POPP entities, edge relations, organization invariant, principles-as-culture, events.",
  },
  {
    name: "sync-model",
    uri: "portuni://sync-model",
    text: SYNC_MODEL_MD,
    title: "Portuni file sync model",
    description:
      "Local mirrors, sync_key paths, status workflow, confirm-first patterns, data-safety defaults, session discipline.",
  },
  {
    name: "scope-rules",
    uri: "portuni://scope-rules",
    text: SCOPE_RULES_MD,
    title: "Portuni read scope",
    description:
      "Session scope set, refusal contract, expand_scope semantics, session types, hard-floor rules.",
  },
  {
    name: "enums",
    uri: "portuni://enums",
    text: ENUMS_MD,
    title: "Portuni enums",
    description:
      "Closed sets: node types, edge relations, statuses, lifecycle states, project health, visibility, event types/statuses, file statuses.",
  },
];

export function registerResources(server: McpServer): void {
  for (const r of RESOURCES) {
    server.registerResource(
      r.name,
      r.uri,
      {
        title: r.title,
        description: r.description,
        mimeType: "text/markdown",
      },
      async (uri) => {
        // Bodies are compiled-in string constants (resources-text.ts,
        // generated by scripts/gen-mcp-resources.mjs from the .md files in
        // this directory), not read from disk at runtime: the sidecar is
        // compiled with `bun build --compile`, which only bundles what is
        // statically imported, so a runtime readFile against
        // import.meta.url resolved to a virtual path with no real file
        // behind it in the compiled binary (#255). A plain string import
        // compiles/bundles identically under tsc+node, tsx and
        // bun --compile -- one code path for every runtime.
        return {
          contents: [
            {
              uri: uri.toString(),
              mimeType: "text/markdown",
              text: r.text,
            },
          ],
        };
      },
    );
  }
}
